#pragma once

#include <memory>
#include <utility>
#include <list>
#include <map>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <iostream>
#include <string>
#include <cstdlib>
#include <cstring>
#include <typeinfo>
#include <stdio.h>
#include <time.h>
#include <stdarg.h>
#include <assert.h>
#include <math.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <unordered_map>
#include <fcntl.h>
#include <sstream>
#include <algorithm>
#include <vector>
#include <unordered_set>
#include <set>
#include <thread>
#include <mutex>
#include <dirent.h>
#include <chrono>
#include <pthread.h>
#include <stack>
#include <functional>
#include <queue>
#include <condition_variable>
#include <future>
#include <stdexcept>
#include <deque>
#include <cassert>
#include <cstdint>
#include <string.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <variant>

// include glog here, so that we can use glog in all files
// and maybe someday we can replace glog with our own log
#include "glog/logging.h"
