include("N:/project/fakelua/build_cov/cmake/CPM_0.38.7.cmake")
CPMAddPackage("NAME;gflags;GITHUB_REPOSITORY;gflags/gflags;GIT_TAG;v2.2.2;OPTIONS;BUILD_SHARED_LIBS OFF;INSTALL_HEADERS ON;INSTALL_SHARED_LIBS ON;INSTALL_STATIC_LIBS ON;REGISTER_INSTALL_PREFIX ON;BUILD_TESTING OFF")
set(gflags_FOUND TRUE)