#include "compile/c_gen.h"

#include <ranges>

#include "state/state.h"
#include "util/common.h"
#include "util/exception.h"
#include "util/file_util.h"

namespace fakelua {

CGen::CGen(State *s) : s_(s), func_compiler_(s) {
}

GenResult CGen::Generate(const ParseResult &pr, const InferResult &ir, const CompileConfig &cfg) {
    LOG_INFO("start CGen::Generate {}", pr.file_name);

    file_name_ = pr.file_name;

    // 生成代码
    GenResult gr = Build(pr, ir, cfg);

    if (cfg.debug_mode) {
        const auto dumpfile = GenerateTmpFilename("fakelua_jit_", ".c");
        if (std::ofstream ofs(dumpfile); ofs.is_open()) {
            ofs << gr.c_code;
            ofs.close();
            std::cerr << "CGen::Generate: C code dumped to " << dumpfile << std::endl;
            LOG_INFO("C code generated: {}", dumpfile);
        } else {
            LOG_ERROR("Failed to open output file: {}", dumpfile);
        }
    }

    LOG_INFO("end CGen::Generate {}, functions: {}", pr.file_name, gr.function_names.size());
    return gr;
}

GenResult CGen::Build(const ParseResult &pr, const InferResult &ir, const CompileConfig &cfg) {
    // 加载数学参数分析结果，供 GenerateDecls 和 GenerateImpl 使用。
    math_param_positions_ = ir.math_param_positions;
    specialization_snapshots_ = &ir.specialization_snapshots;
    specialization_return_types_ = &ir.specialization_return_types;
    main_eval_types_ = &ir.main_eval_types;

    // 注入上下文指针，供 FuncBodyCompiler 在语句/表达式编译中使用。
    func_compiler_.SetContext(
            &file_name_,
            &local_func_names_,
            &global_const_vars_,
            &in_global_init_,
            &tmp_var_counter_,
            &math_param_positions_,
            specialization_snapshots_,
            specialization_return_types_,
            main_eval_types_);

    GenResult gr;
    cur_output_ = &headers_;
    GenerateHeader();
    cur_output_ = &globals_;
    GenerateGlobal(pr.chunk);
    cur_output_ = &decls_;
    GenerateDecls(pr.chunk, gr);
    local_func_names_ = gr.function_names;
    cur_output_ = &impls_;
    GenerateImpl(pr.chunk, gr);
    if (cfg.record_c_code) {
        // 仅记录非头部部分（全局变量 + 声明 + 实现）。
        // 头部是每个编译单元相同的固定样板代码，对类型推断断言没有用处。
        gr.recorded_c_code = globals_.str() + decls_.str() + impls_.str();
    }
    gr.c_code = headers_.str() + globals_.str() + decls_.str() + impls_.str();
    return gr;
}

void CGen::GenerateHeader() {
    *cur_output_ << R"(// Generated by FakeLua CGen
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <stdlib.h>
#include <stdio.h>

)";

    // 硬编码 state 指针到生成的 C 代码中。
    // 生命周期保证：生成的代码最终由 TCCState/GCC 产物承载，这些产物通过 TCCHandle/JITHandle
    // 被 VmFunction 以 shared_ptr 持有，而 VmFunction 注册在本 State 的 Vm 中（见
    // src/jit/tcc_jit.cpp 与 src/jit/vm_function.h）。因此生成代码里的 _S 永远不会
    // 比其宿主 State 活得更久——State 析构即销毁 Vm，进而释放 handle 和代码页。
    // 同一份代码也不会被跨 State 复用（每次编译都会重新生成）。
    *cur_output_ << "static void * _S = (void *) " << s_ << ";\n";

    *cur_output_ << R"(
typedef struct VarString {
    int size_;
    uint32_t hash_;
    char data_[0];
} VarString;

typedef struct VarTable VarTable;

typedef struct CVar {
    int type_;
    int flag_;
    union {
        bool b;
        int64_t i;
        double f;
        VarString *s;
        VarTable *t;
    } data_;
} CVar;

// 编译期断言：确保 CVar 大小为 16 字节
typedef char check_cvar_size[sizeof(CVar) == 16 ? 1 : -1];

typedef struct VarEntry {
    CVar key;
    CVar val;
    uint32_t hash;
} VarEntry;

typedef struct TableNode {
    VarEntry entry;
    uint32_t next;
    uint32_t active_pos;
} TableNode;

struct VarTable {
    uint32_t count_;
    uint32_t bucket_count_;
    TableNode *nodes_;
    uint32_t *active_list_;
    VarEntry quick_data_[8];
    uint32_t free_list_idx_;
};

typedef struct State State;

#define STR_SIZE(s) ((s)->size_)
#define STR_DATA(s) ((s)->data_)
#define TABLE_SIZE(t) ((t)->count_)

enum {
    VAR_NIL = 0,
    VAR_BOOL = 1,
    VAR_INT = 2,
    VAR_FLOAT = 3,
    VAR_STRING = 4,
    VAR_STRINGID = 5,
    VAR_TABLE = 6,
};

#define SET_NIL(v) do { (v).type_ = VAR_NIL; } while(0)
#define SET_BOOL(v, val) do { (v).type_ = VAR_BOOL; (v).data_.b = (val); } while(0)
#define SET_INT(v, val) do { (v).type_ = VAR_INT; (v).data_.i = (val); } while(0)
#define SET_FLOAT(v, val) do { \
    double __f = (val); \
    (v).type_ = VAR_FLOAT; \
    (v).data_.f = __f; \
} while(0)

// 规范化表键以匹配 Lua 行为：
// 整数浮点键被视为整数键（例如 t[2.0] == t[2]）。
// 边界检查说明：(double)INT64_MAX 因浮点精度向上取整为 2^63，使用 '<=' 而非 '<'：
// 实践中 IEEE 754 double 在 2^62～2^63 步进为 512，modf 不会产生恰好等于 2^63 的
// 中间值，因此该检查对所有真实可达的浮点整数值均正确。与 Lua 5.4 官方实现一致。
#define NORMALIZE_TABLE_KEY(key) ({ \
    CVar __k = (key); \
    if (__k.type_ == VAR_FLOAT) { \
        double __d = __k.data_.f; \
        if (isfinite(__d)) { \
            double __ip; \
            if (modf(__d, &__ip) == 0.0 && __ip >= (double)INT64_MIN && __ip <= (double)INT64_MAX) { \
                __k.type_ = VAR_INT; \
                __k.data_.i = (int64_t)__ip; \
            } \
        } \
    } \
    __k; \
})

// 用于内存分配和错误处理的外部函数
extern void* FakeluaAllocTemp(State *s, size_t size);
extern void FakeluaThrowError(State *s, const char *msg);
extern CVar FakeluaCallByName(State *s, int jit_type, const char *name, int arg_num, ...);

#ifndef FAKELUA_JIT_TYPE
#define FAKELUA_JIT_TYPE 0
#endif

static inline uint32_t FlHashString(const char *str, int len) {
    uint32_t hash = 5381;
    int i;
    for (i = 0; i < len; ++i) {
        hash = ((hash << 5) + hash) + (uint8_t)str[i];
    }
    if (hash == 0) {
        hash = 1;
    }
    return hash;
}

#define SET_STRING(v, str, len) do { \
    int __len = (len); \
    const char *__s_ptr = (str); \
    VarString *__vs = (VarString *)FakeluaAllocTemp(_S, sizeof(VarString) + __len); \
    __vs->size_ = __len; \
    __vs->hash_ = 0; \
    memcpy(__vs->data_, __s_ptr, __len); \
    (v).type_ = VAR_STRING; \
    (v).data_.s = __vs; \
} while(0)

#define SET_TABLE(v) do { \
    VarTable *__t = (VarTable *)FakeluaAllocTemp(_S, sizeof(VarTable)); \
    __t->count_ = 0; \
    __t->bucket_count_ = 0; \
    __t->nodes_ = NULL; \
    __t->active_list_ = NULL; \
    __t->free_list_idx_ = 0xFFFFFFFF; \
    assert(sizeof(__t->quick_data_) == 8 * sizeof(VarEntry)); \
    { int __i; for (__i = 0; __i < 8; ++__i) { \
        __t->quick_data_[__i].key.type_ = VAR_NIL; \
        __t->quick_data_[__i].val.type_ = VAR_NIL; \
        __t->quick_data_[__i].hash = 0; \
    } } \
    (v).type_ = VAR_TABLE; \
    (v).data_.t = __t; \
} while(0)

// 逻辑和相等性宏
#define IsTrue(v, result) do { \
    CVar __tv = (v); \
    (result) = (__tv.type_ != VAR_NIL && (__tv.type_ != VAR_BOOL || __tv.data_.b)); \
} while(0)

#define VarEqual(_fa, _fb, result) do { \
    CVar __a = (_fa), __b = (_fb); \
    if (__a.type_ != __b.type_) { \
        if ((__a.type_ == VAR_STRING || __a.type_ == VAR_STRINGID) && \
            (__b.type_ == VAR_STRING || __b.type_ == VAR_STRINGID)) { \
            VarString *__sa = (__a.type_ == VAR_STRING) ? __a.data_.s : (VarString *)__a.data_.i; \
            VarString *__sb = (__b.type_ == VAR_STRING) ? __b.data_.s : (VarString *)__b.data_.i; \
            if (__sa == __sb) { (result) = true; break; } \
            (result) = (__sa->size_ == __sb->size_ && memcmp(__sa->data_, __sb->data_, __sa->size_) == 0); \
        } else if (__a.type_ == VAR_INT && __b.type_ == VAR_FLOAT) { \
            (result) = ((double)__a.data_.i == __b.data_.f); \
        } else if (__a.type_ == VAR_FLOAT && __b.type_ == VAR_INT) { \
            (result) = (__a.data_.f == (double)__b.data_.i); \
        } else { \
            (result) = false; \
        } \
        break; \
    } \
    switch (__a.type_) { \
        case VAR_NIL: (result) = true; break; \
        case VAR_BOOL: (result) = (__a.data_.b == __b.data_.b); break; \
        case VAR_INT: (result) = (__a.data_.i == __b.data_.i); break; \
        case VAR_FLOAT: (result) = (__a.data_.f == __b.data_.f); break; \
        case VAR_STRING: { \
            if (__a.data_.s == __b.data_.s) { (result) = true; break; } \
            (result) = (__a.data_.s->size_ == __b.data_.s->size_ && memcmp(__a.data_.s->data_, __b.data_.s->data_, __a.data_.s->size_) == 0); \
            break; \
        } \
        case VAR_STRINGID: (result) = (__a.data_.i == __b.data_.i); break; \
        case VAR_TABLE: (result) = (__a.data_.t == __b.data_.t); break; \
        default: (result) = false; break; \
    } \
} while(0)

#define VarHash(v, hash) do { \
    CVar __v = (v); \
    switch (__v.type_) { \
        case VAR_NIL: (hash) = 0; break; \
        case VAR_BOOL: (hash) = (__v.data_.b ? 1 : 0); break; \
        case VAR_INT: (hash) = (uint32_t)(__v.data_.i ^ (__v.data_.i >> 32)); break; \
        case VAR_FLOAT: { union { double __d; uint64_t __u; } __fu; __fu.__d = __v.data_.f; (hash) = (uint32_t)(__fu.__u ^ (__fu.__u >> 32)); break; } \
        case VAR_STRING: { if (__v.data_.s->hash_ == 0) { __v.data_.s->hash_ = FlHashString(__v.data_.s->data_, __v.data_.s->size_); } (hash) = __v.data_.s->hash_; break; } \
        case VAR_STRINGID: { VarString *__vs = (VarString *)__v.data_.i; if (__vs->hash_ == 0) { __vs->hash_ = FlHashString(__vs->data_, __vs->size_); } (hash) = __vs->hash_; break; } \
        case VAR_TABLE: (hash) = (uint32_t)((uintptr_t)__v.data_.t ^ ((uintptr_t)__v.data_.t >> 32)); break; \
        default: (hash) = 0; break; \
    } \
} while(0)

static inline CVar FlGetTable(CVar t, CVar k) {
    k = NORMALIZE_TABLE_KEY(k);
    if (t.type_ != VAR_TABLE) { FakeluaThrowError(_S, "attempt to index a non-table value"); }
    if (k.type_ == VAR_NIL) { FakeluaThrowError(_S, "table index is nil"); }
    VarTable *tbl = t.data_.t;
    if (tbl->count_ == 0) { return (CVar){VAR_NIL}; }
    uint32_t h; VarHash(k, h);
    if (tbl->bucket_count_ == 0) {
        bool __eq;
        if (tbl->quick_data_[0].hash == h) { VarEqual(tbl->quick_data_[0].key, k, __eq); if (__eq) { return tbl->quick_data_[0].val; } }
        if (tbl->count_ > 1 && tbl->quick_data_[1].hash == h) { VarEqual(tbl->quick_data_[1].key, k, __eq); if (__eq) { return tbl->quick_data_[1].val; } }
        if (tbl->count_ > 2 && tbl->quick_data_[2].hash == h) { VarEqual(tbl->quick_data_[2].key, k, __eq); if (__eq) { return tbl->quick_data_[2].val; } }
        if (tbl->count_ > 3 && tbl->quick_data_[3].hash == h) { VarEqual(tbl->quick_data_[3].key, k, __eq); if (__eq) { return tbl->quick_data_[3].val; } }
        if (tbl->count_ > 4 && tbl->quick_data_[4].hash == h) { VarEqual(tbl->quick_data_[4].key, k, __eq); if (__eq) { return tbl->quick_data_[4].val; } }
        if (tbl->count_ > 5 && tbl->quick_data_[5].hash == h) { VarEqual(tbl->quick_data_[5].key, k, __eq); if (__eq) { return tbl->quick_data_[5].val; } }
        if (tbl->count_ > 6 && tbl->quick_data_[6].hash == h) { VarEqual(tbl->quick_data_[6].key, k, __eq); if (__eq) { return tbl->quick_data_[6].val; } }
        if (tbl->count_ > 7 && tbl->quick_data_[7].hash == h) { VarEqual(tbl->quick_data_[7].key, k, __eq); if (__eq) { return tbl->quick_data_[7].val; } }
    } else {
        uint32_t mask = tbl->bucket_count_ - 1;
        uint32_t idx = h & mask;
        TableNode *curr = &tbl->nodes_[idx];
        if (curr->entry.key.type_ == VAR_NIL) { return (CVar){VAR_NIL}; }
        while (1) {
            if (curr->entry.hash == h) { bool __eq; VarEqual(curr->entry.key, k, __eq); if (__eq) { return curr->entry.val; } }
            uint32_t next = curr->next;
            if (next == 0xFFFFFFFF) { break; }
            curr = &tbl->nodes_[next];
        }
    }
    return (CVar){VAR_NIL};
}

static inline uint32_t NextPowerOfTwo(uint32_t v) {
    v--; v |= v >> 1; v |= v >> 2; v |= v >> 4; v |= v >> 8; v |= v >> 16; v++;
    return v;
}

static inline bool FlTableInsertRaw(VarTable *tbl, CVar key, CVar val, uint32_t hash) {
    uint32_t mask = tbl->bucket_count_ - 1;
    uint32_t total_nodes = tbl->bucket_count_ + tbl->bucket_count_ / 2;
    assert(tbl->count_ < total_nodes);
    uint32_t idx = hash & mask;
    TableNode *main_node = &tbl->nodes_[idx];
    if (main_node->entry.key.type_ == VAR_NIL) {
        main_node->entry.key = key; main_node->entry.val = val; main_node->entry.hash = hash; main_node->next = 0xFFFFFFFF;
        main_node->active_pos = tbl->count_; tbl->active_list_[tbl->count_] = idx;
        tbl->count_++; return true;
    }
    uint32_t curr_idx = idx;
    while (1) {
        TableNode *curr = &tbl->nodes_[curr_idx];
        if (curr->entry.hash == hash) { bool __eq; VarEqual(curr->entry.key, key, __eq); if (__eq) { curr->entry.val = val; return true; } }
        if (curr->next == 0xFFFFFFFF) { break; }
        curr_idx = curr->next;
    }
    if (tbl->free_list_idx_ == 0xFFFFFFFF) { return false; }
    uint32_t new_node_idx = tbl->free_list_idx_;
    TableNode *new_node = &tbl->nodes_[new_node_idx];
    tbl->free_list_idx_ = new_node->next;
    new_node->entry.key = key; new_node->entry.val = val; new_node->entry.hash = hash;
    new_node->next = main_node->next; main_node->next = new_node_idx;
    new_node->active_pos = tbl->count_; tbl->active_list_[tbl->count_] = new_node_idx;
    tbl->count_++; return true;
}

static inline void FlTableRehash(VarTable *tbl) {
    uint32_t old_count = tbl->count_;
    uint32_t old_bucket_count = tbl->bucket_count_;
    TableNode *old_nodes = tbl->nodes_;
    uint32_t new_bucket_count = NextPowerOfTwo(old_count + 1);
    if (new_bucket_count <= old_bucket_count) { new_bucket_count = old_bucket_count * 2; }
    while (1) {
        uint32_t overflow_count = new_bucket_count / 2;
        uint32_t total_nodes = new_bucket_count + overflow_count;
        size_t nodes_size = total_nodes * sizeof(TableNode);
        size_t active_list_size = total_nodes * sizeof(uint32_t);
        char *buffer = (char *)FakeluaAllocTemp(_S, nodes_size + active_list_size);
        TableNode *new_nodes = (TableNode *)buffer;
        uint32_t *new_active_list = (uint32_t *)(buffer + nodes_size);
        { uint32_t i; for (i = 0; i < total_nodes; ++i) { new_nodes[i].entry.key.type_ = VAR_NIL; new_nodes[i].next = 0xFFFFFFFF; new_nodes[i].active_pos = 0xFFFFFFFF; } }
        TableNode *prev_nodes = tbl->nodes_; uint32_t *prev_active_list = tbl->active_list_; uint32_t prev_bucket_count = tbl->bucket_count_; uint32_t prev_count = tbl->count_; uint32_t prev_free_list_idx = tbl->free_list_idx_;
        tbl->nodes_ = new_nodes; tbl->active_list_ = new_active_list; tbl->bucket_count_ = new_bucket_count; tbl->count_ = 0;
        if (overflow_count > 0) {
            { uint32_t i; for (i = 0; i < overflow_count - 1; ++i) { tbl->nodes_[new_bucket_count + i].next = new_bucket_count + i + 1; } }
            tbl->nodes_[new_bucket_count + overflow_count - 1].next = 0xFFFFFFFF;
            tbl->free_list_idx_ = new_bucket_count;
        } else {
            tbl->free_list_idx_ = 0xFFFFFFFF;
        }
        bool success = true;
        if (old_bucket_count == 0) {
            { uint32_t i; for (i = 0; i < old_count; ++i) { if (!FlTableInsertRaw(tbl, tbl->quick_data_[i].key, tbl->quick_data_[i].val, tbl->quick_data_[i].hash)) { success = false; break; } } }
        } else {
            { uint32_t i; for (i = 0; i < old_bucket_count; ++i) {
                uint32_t curr_idx = i;
                while (curr_idx != 0xFFFFFFFF) {
                    TableNode *old_node = &old_nodes[curr_idx];
                    if (old_node->entry.key.type_ != VAR_NIL) { if (!FlTableInsertRaw(tbl, old_node->entry.key, old_node->entry.val, old_node->entry.hash)) { success = false; break; } }
                    curr_idx = old_node->next;
                }
                if (!success) { break; }
            } }
        }
        if (success) { break; } else { tbl->nodes_ = prev_nodes; tbl->active_list_ = prev_active_list; tbl->bucket_count_ = prev_bucket_count; tbl->count_ = prev_count; tbl->free_list_idx_ = prev_free_list_idx; new_bucket_count *= 2; }
    }
}

static inline void FlSetTable(CVar t, CVar k, CVar v) {
    k = NORMALIZE_TABLE_KEY(k);
    if (t.type_ != VAR_TABLE) { FakeluaThrowError(_S, "attempt to index a non-table value"); }
    if (k.type_ == VAR_NIL) { FakeluaThrowError(_S, "table index is nil"); }
    VarTable *tbl = t.data_.t; uint32_t h; VarHash(k, h);
    if (v.type_ == VAR_NIL) {
        if (tbl->count_ == 0) { return; }
        if (tbl->bucket_count_ == 0) {
            bool __eq;
            if (tbl->quick_data_[0].hash == h) { VarEqual(tbl->quick_data_[0].key, k, __eq); if (__eq) { if (tbl->count_ > 1) { tbl->quick_data_[0] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 1 && tbl->quick_data_[1].hash == h) { VarEqual(tbl->quick_data_[1].key, k, __eq); if (__eq) { if (tbl->count_ > 2) { tbl->quick_data_[1] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 2 && tbl->quick_data_[2].hash == h) { VarEqual(tbl->quick_data_[2].key, k, __eq); if (__eq) { if (tbl->count_ > 3) { tbl->quick_data_[2] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 3 && tbl->quick_data_[3].hash == h) { VarEqual(tbl->quick_data_[3].key, k, __eq); if (__eq) { if (tbl->count_ > 4) { tbl->quick_data_[3] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 4 && tbl->quick_data_[4].hash == h) { VarEqual(tbl->quick_data_[4].key, k, __eq); if (__eq) { if (tbl->count_ > 5) { tbl->quick_data_[4] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 5 && tbl->quick_data_[5].hash == h) { VarEqual(tbl->quick_data_[5].key, k, __eq); if (__eq) { if (tbl->count_ > 6) { tbl->quick_data_[5] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 6 && tbl->quick_data_[6].hash == h) { VarEqual(tbl->quick_data_[6].key, k, __eq); if (__eq) { if (tbl->count_ > 7) { tbl->quick_data_[6] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 7 && tbl->quick_data_[7].hash == h) { VarEqual(tbl->quick_data_[7].key, k, __eq); if (__eq) { tbl->count_--; return; } }
        } else {
            uint32_t mask = tbl->bucket_count_ - 1; uint32_t idx = h & mask; TableNode *curr = &tbl->nodes_[idx];
            if (curr->entry.key.type_ == VAR_NIL) { return; }
            { bool __eq; VarEqual(curr->entry.key, k, __eq); if (curr->entry.hash == h && __eq) {
                if (curr->next != 0xFFFFFFFF) {
                    uint32_t next_idx = curr->next; TableNode *next_node = &tbl->nodes_[next_idx];
                    uint32_t pos = next_node->active_pos; uint32_t last_node_idx = tbl->active_list_[tbl->count_ - 1];
                    if (next_idx != last_node_idx) { tbl->active_list_[pos] = last_node_idx; tbl->nodes_[last_node_idx].active_pos = pos; }
                    next_node->active_pos = 0xFFFFFFFF; curr->entry = next_node->entry; curr->next = next_node->next; next_node->next = tbl->free_list_idx_; tbl->free_list_idx_ = next_idx;
                } else {
                    uint32_t pos = curr->active_pos; uint32_t last_node_idx = tbl->active_list_[tbl->count_ - 1];
                    if (idx != last_node_idx) { tbl->active_list_[pos] = last_node_idx; tbl->nodes_[last_node_idx].active_pos = pos; }
                    curr->active_pos = 0xFFFFFFFF; curr->entry.key.type_ = VAR_NIL;
                }
                tbl->count_--; return;
            } }
            uint32_t prev_idx = idx; uint32_t curr_idx = curr->next;
            while (curr_idx != 0xFFFFFFFF) {
                TableNode *node = &tbl->nodes_[curr_idx];
                { bool __eq; VarEqual(node->entry.key, k, __eq); if (node->entry.hash == h && __eq) {
                    uint32_t pos = node->active_pos; uint32_t last_node_idx = tbl->active_list_[tbl->count_ - 1];
                    if (curr_idx != last_node_idx) { tbl->active_list_[pos] = last_node_idx; tbl->nodes_[last_node_idx].active_pos = pos; }
                    node->active_pos = 0xFFFFFFFF; tbl->nodes_[prev_idx].next = node->next; node->next = tbl->free_list_idx_; tbl->free_list_idx_ = curr_idx; tbl->count_--; return;
                } }
                prev_idx = curr_idx; curr_idx = node->next;
            }
        }
        return;
    }
    if (tbl->bucket_count_ == 0) {
        bool __eq;
        if (tbl->count_ > 0 && tbl->quick_data_[0].hash == h) { VarEqual(tbl->quick_data_[0].key, k, __eq); if (__eq) { tbl->quick_data_[0].val = v; return; } }
        if (tbl->count_ > 1 && tbl->quick_data_[1].hash == h) { VarEqual(tbl->quick_data_[1].key, k, __eq); if (__eq) { tbl->quick_data_[1].val = v; return; } }
        if (tbl->count_ > 2 && tbl->quick_data_[2].hash == h) { VarEqual(tbl->quick_data_[2].key, k, __eq); if (__eq) { tbl->quick_data_[2].val = v; return; } }
        if (tbl->count_ > 3 && tbl->quick_data_[3].hash == h) { VarEqual(tbl->quick_data_[3].key, k, __eq); if (__eq) { tbl->quick_data_[3].val = v; return; } }
        if (tbl->count_ > 4 && tbl->quick_data_[4].hash == h) { VarEqual(tbl->quick_data_[4].key, k, __eq); if (__eq) { tbl->quick_data_[4].val = v; return; } }
        if (tbl->count_ > 5 && tbl->quick_data_[5].hash == h) { VarEqual(tbl->quick_data_[5].key, k, __eq); if (__eq) { tbl->quick_data_[5].val = v; return; } }
        if (tbl->count_ > 6 && tbl->quick_data_[6].hash == h) { VarEqual(tbl->quick_data_[6].key, k, __eq); if (__eq) { tbl->quick_data_[6].val = v; return; } }
        if (tbl->count_ > 7 && tbl->quick_data_[7].hash == h) { VarEqual(tbl->quick_data_[7].key, k, __eq); if (__eq) { tbl->quick_data_[7].val = v; return; } }
        if (tbl->count_ < 8) { tbl->quick_data_[tbl->count_].key = k; tbl->quick_data_[tbl->count_].val = v; tbl->quick_data_[tbl->count_].hash = h; tbl->count_++; return; }
        FlTableRehash(tbl);
    }
    if (tbl->count_ >= tbl->bucket_count_ || tbl->free_list_idx_ == 0xFFFFFFFF) { FlTableRehash(tbl); }
    FlTableInsertRaw(tbl, k, v, h);
}

// 算术和比较宏（表达式风格）
// 为提高性能，算术运算仅支持整数和浮点类型。

#define CheckNum(v) do { \
    if ((v).type_ != VAR_INT && (v).type_ != VAR_FLOAT) { \
        FakeluaThrowError(_S, "attempt to perform arithmetic on non-numeric value"); \
    } \
} while(0)

#define CheckInt(v, result) do { \
    if ((v).type_ == VAR_INT) { (result) = (v).data_.i; } \
    else if ((v).type_ == VAR_FLOAT) { \
        double __d = (v).data_.f; \
        if (!isfinite(__d)) { FakeluaThrowError(_S, "number has no integer representation"); } \
        double __ip; \
        if (modf(__d, &__ip) != 0.0) { FakeluaThrowError(_S, "number has no integer representation"); } \
        /* 边界检查：(double)INT64_MAX 因浮点精度向上取整为 2^63，使用 '>' 而非 '>='。  */ \
        /* 实践中 modf 不产生恰好等于 2^63 的中间值，与 Lua 5.4 官方实现一致。          */ \
        if (__ip < (double)INT64_MIN || __ip > (double)INT64_MAX) { FakeluaThrowError(_S, "number has no integer representation"); } \
        (result) = (int64_t)__ip; \
    } else { \
        FakeluaThrowError(_S, "attempt to perform bitwise operation on non-numeric value"); \
        (result) = 0; \
    } \
} while(0)

#define OpAdd(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_INT(res, _ra.data_.i + _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_FLOAT(res, _f1 + _f2); } \
} while(0)

#define OpSub(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_INT(res, _ra.data_.i - _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_FLOAT(res, _f1 - _f2); } \
} while(0)

#define OpMul(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_INT(res, _ra.data_.i * _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_FLOAT(res, _f1 * _f2); } \
} while(0)

#define OpDiv(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
    double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
    SET_FLOAT(res, _f1 / _f2); \
} while(0)

#define OpFloorDiv(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { \
        if (_rb.data_.i == 0) { FakeluaThrowError(_S, "floor division by zero"); } \
        /* UB 说明（有意保留）：当 _ra==INT64_MIN 且 _rb==-1 时，/ 和 % 均触发有符号溢出 UB。 */ \
        /* Lua 5.4 官方实现同样未特判，x86-64 IDIV 硬件行为稳定，为性能不加额外分支。 */ \
        int64_t _q = _ra.data_.i / _rb.data_.i; \
        if ((_ra.data_.i ^ _rb.data_.i) < 0 && _ra.data_.i % _rb.data_.i != 0) { _q -= 1; } \
        SET_INT(res, _q); \
    } else { \
        double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
        double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
        SET_FLOAT(res, floor(_f1 / _f2)); \
    } \
} while(0)

#define OpPow(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
    double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
    SET_FLOAT(res, pow(_f1, _f2)); \
} while(0)

#define OpMod(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { \
        if (_rb.data_.i == 0) { FakeluaThrowError(_S, "modulo by zero"); } \
        /* UB 说明（有意保留）：当 _ra==INT64_MIN 且 _rb==-1 时，/ 和 % 均触发有符号溢出 UB。 */ \
        /* Lua 5.4 官方实现同样未特判，x86-64 IDIV 硬件行为稳定，为性能不加额外分支。 */ \
        int64_t _q = _ra.data_.i / _rb.data_.i; \
        if ((_ra.data_.i ^ _rb.data_.i) < 0 && _ra.data_.i % _rb.data_.i != 0) { _q -= 1; } \
        SET_INT(res, _ra.data_.i - _rb.data_.i * _q); \
    } else { \
        double _fa = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
        double _fb = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
        SET_FLOAT(res, _fa - _fb * floor(_fa / _fb)); \
    } \
} while(0)

#define OpBitAnd(a, b, res) do { int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); SET_INT(res, _ai & _bi); } while(0)

#define OpBitXor(a, b, res) do { int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); SET_INT(res, _ai ^ _bi); } while(0)

#define OpBitOr(a, b, res) do { int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); SET_INT(res, _ai | _bi); } while(0)

#define OpRightShift(a, b, res) do { \
    int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); \
    if (_bi >= 64 || _bi <= -64) { SET_INT(res, 0); } \
    else if (_bi >= 0) { SET_INT(res, (int64_t)((uint64_t)_ai >> _bi)); } \
    else { SET_INT(res, (int64_t)((uint64_t)_ai << (-(int64_t)_bi))); } \
} while(0)

#define OpLeftShift(a, b, res) do { \
    int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); \
    if (_bi >= 64 || _bi <= -64) { SET_INT(res, 0); } \
    else if (_bi >= 0) { SET_INT(res, (int64_t)((uint64_t)_ai << _bi)); } \
    else { SET_INT(res, (int64_t)((uint64_t)_ai >> (-(int64_t)_bi))); } \
} while(0)

#define OpLt(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i < _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 < _f2); } \
} while(0)

#define OpGt(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i > _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 > _f2); } \
} while(0)

#define OpLe(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i <= _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 <= _f2); } \
} while(0)

#define OpGe(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i >= _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 >= _f2); } \
} while(0)

#define OpEq(a, b, res) do { bool _eq; VarEqual(a, b, _eq); SET_BOOL(res, _eq); } while(0)

#define OpNe(a, b, res) do { bool _eq; VarEqual(a, b, _eq); SET_BOOL(res, !_eq); } while(0)

#define OpNot(a, res) do { bool _bt; IsTrue(a, _bt); SET_BOOL(res, !_bt); } while(0)

#define OpUnaryMinus(a, res) do { \
    CVar _ra = (a); CheckNum(_ra); \
    /* UB 说明（有意保留）：-INT64_MIN 触发有符号整数溢出 UB。 */ \
    /* Lua 5.4 官方实现同样未特判，x86-64 NEG 指令行为稳定，为性能不加额外分支。 */ \
    if (_ra.type_ == VAR_INT) { SET_INT(res, -_ra.data_.i); } \
    else { SET_FLOAT(res, -_ra.data_.f); } \
} while(0)

#define OpBitNot(a, res) do { int64_t _ai; CheckInt(a, _ai); SET_INT(res, ~_ai); } while(0)

#define OpLen(a, res) do { \
    CVar _lv = (a); \
    if (_lv.type_ == VAR_STRING) { SET_INT(res, STR_SIZE(_lv.data_.s)); } \
    else if (_lv.type_ == VAR_STRINGID) { SET_INT(res, STR_SIZE((VarString *)_lv.data_.i)); } \
    else if (_lv.type_ == VAR_TABLE) { SET_INT(res, TABLE_SIZE(_lv.data_.t)); } \
    else { FakeluaThrowError(_S, "attempt to get length of a non-string/table value"); } \
} while(0)

static inline int FlVarToStr(CVar v, char *buf, int buf_size) {
    switch (v.type_) {
        case VAR_NIL: memcpy(buf, "nil", 3); buf[3] = '\0'; return 3;
        case VAR_BOOL: if (v.data_.b) { memcpy(buf, "true", 4); buf[4] = '\0'; return 4; } else { memcpy(buf, "false", 5); buf[5] = '\0'; return 5; }
        case VAR_INT: return snprintf(buf, buf_size, "%lld", (long long)v.data_.i);
        case VAR_FLOAT: return snprintf(buf, buf_size, "%.17g", v.data_.f);
        case VAR_STRING:
        case VAR_STRINGID: FakeluaThrowError(_S, "FlVarToStr: string type should be handled by caller"); return 0;
        default: { int __n = snprintf(buf, buf_size - 1, "table(0x%llx", (unsigned long long)(uintptr_t)v.data_.t); if (__n > 0 && __n < buf_size - 1) { buf[__n] = ')'; buf[__n + 1] = '\0'; return __n + 1; } return __n; }
    }
}

static inline CVar FlConcat(CVar a, CVar b) {
    char buf_a[256], buf_b[256];
    const char *sa = buf_a; int la;
    const char *sb = buf_b; int lb;
    /* 转换 a */
    if (a.type_ == VAR_STRING) { sa = STR_DATA(a.data_.s); la = STR_SIZE(a.data_.s); }
    else if (a.type_ == VAR_STRINGID) { VarString *vs = (VarString *)a.data_.i; sa = STR_DATA(vs); la = STR_SIZE(vs); }
    else { la = FlVarToStr(a, buf_a, sizeof(buf_a)); }
    /* 转换 b */
    if (b.type_ == VAR_STRING) { sb = STR_DATA(b.data_.s); lb = STR_SIZE(b.data_.s); }
    else if (b.type_ == VAR_STRINGID) { VarString *vs = (VarString *)b.data_.i; sb = STR_DATA(vs); lb = STR_SIZE(vs); }
    else { lb = FlVarToStr(b, buf_b, sizeof(buf_b)); }
    /* 分配结果 */
    /* 溢出检查说明：la 和 lb 均来自 arena 分配的字符串（单块上限 1MB）或 snprintf 的 256
       字节缓冲区，两者之和远小于 INT_MAX（约 2^31），因此 'int total = la + lb' 不会
       真正溢出。此处的 'total < la || total < lb' 是防御性检查，覆盖理论上的极端场景。 */
    int total = la + lb;
    if (total < la || total < lb) { FakeluaThrowError(_S, "string concatenation result too long"); }
    VarString *vs = (VarString *)FakeluaAllocTemp(_S, sizeof(VarString) + total);
    vs->size_ = total;
    vs->hash_ = 0;
    memcpy(vs->data_, sa, la);
    memcpy(vs->data_ + la, sb, lb);
    CVar result;
    result.type_ = VAR_STRING;
    result.flag_ = 0;
    result.data_.s = vs;
    return result;
}

// GET_TABLE_ENTRY(tbl, idx, k, v): 从 CVar 表中获取活跃索引 idx 处的键和值。
// 适用于小表模式（bucket_count_ == 0，使用 quick_data_[]）和
// 哈希表模式（使用 active_list_[] + nodes_[]）。
#define GET_TABLE_ENTRY(tbl, idx, k, v) do { \
    if ((tbl).data_.t->bucket_count_ == 0) { \
        (k) = (tbl).data_.t->quick_data_[(idx)].key; \
        (v) = (tbl).data_.t->quick_data_[(idx)].val; \
    } else { \
        uint32_t __gti_node_idx = (tbl).data_.t->active_list_[(idx)]; \
        (k) = (tbl).data_.t->nodes_[__gti_node_idx].entry.key; \
        (v) = (tbl).data_.t->nodes_[__gti_node_idx].entry.val; \
    } \
} while(0)

// 原生整数向下取整除法（Lua 语义：向负无穷方向取整）。
// 与 OpFloorDiv 的 VAR_INT 分支保持完全一致的语义。
// UB 说明（有意保留）：当 a==INT64_MIN 且 b==-1 时，/ 和 % 均触发有符号溢出 UB。
// Lua 5.4 官方实现同样未特判，x86-64 IDIV 硬件行为稳定，为性能不加额外分支。
#define FlFloorDivInt(a, b, result) do { \
    int64_t __fl_a = (a); int64_t __fl_b = (b); \
    if (__fl_b == 0) { FakeluaThrowError(_S, "floor division by zero"); } \
    int64_t __fl_q = __fl_a / __fl_b; \
    if ((__fl_a ^ __fl_b) < 0 && __fl_a % __fl_b != 0) { __fl_q -= 1; } \
    (result) = __fl_q; \
} while(0)

// 原生整数取模（Lua 语义：a - b * floor(a/b)）。
// 与 OpMod 的 VAR_INT 分支保持完全一致的语义。
// UB 说明（有意保留）：当 a==INT64_MIN 且 b==-1 时，/ 和 % 均触发有符号溢出 UB。
// Lua 5.4 官方实现同样未特判，x86-64 IDIV 硬件行为稳定，为性能不加额外分支。
#define FlModInt(a, b, result) do { \
    int64_t __fm_a = (a); int64_t __fm_b = (b); \
    if (__fm_b == 0) { FakeluaThrowError(_S, "modulo by zero"); } \
    int64_t __fm_q = __fm_a / __fm_b; \
    if ((__fm_a ^ __fm_b) < 0 && __fm_a % __fm_b != 0) { __fm_q -= 1; } \
    (result) = __fm_a - __fm_b * __fm_q; \
} while(0)

// 原生浮点取模（Lua 语义：a - b * floor(a/b)）。
// 与 OpMod 的 VAR_FLOAT 分支保持一致。
#define FlModFloat(a, b, result) do { \
    double __fmf_a = (a); double __fmf_b = (b); \
    (result) = __fmf_a - __fmf_b * floor(__fmf_a / __fmf_b); \
} while(0)

// 原生整数左移（Lua 语义：负移量反向移位，|移量| >= 64 返回 0，使用 uint64_t 避免符号位 UB）。
// 与 OpLeftShift 的逻辑完全一致，但接受原生 int64_t 参数以省去 CVar 打包/拆包。
#define FlLShiftInt(a, b, result) do { \
    int64_t __ls_a = (a); int64_t __ls_b = (b); \
    if (__ls_b >= 64 || __ls_b <= -64) { \
        (result) = (int64_t)0; \
    } else if (__ls_b >= 0) { \
        (result) = (int64_t)((uint64_t)__ls_a << __ls_b); \
    } else { \
        (result) = (int64_t)((uint64_t)__ls_a >> (-__ls_b)); \
    } \
} while(0)

// 原生整数右移（Lua 语义：负移量反向移位，|移量| >= 64 返回 0，使用 uint64_t 避免符号位 UB）。
// 与 OpRightShift 的逻辑完全一致，但接受原生 int64_t 参数。
#define FlRShiftInt(a, b, result) do { \
    int64_t __rs_a = (a); int64_t __rs_b = (b); \
    if (__rs_b >= 64 || __rs_b <= -64) { \
        (result) = (int64_t)0; \
    } else if (__rs_b >= 0) { \
        (result) = (int64_t)((uint64_t)__rs_a >> __rs_b); \
    } else { \
        (result) = (int64_t)((uint64_t)__rs_a << (-__rs_b)); \
    } \
} while(0)

// 原生取长度：从 CVar 中提取整数长度（字符串字节数或表元素数）。
// 用于在数值特化路径中处理 # 运算符，替代 OpLen 宏以直接返回 int64_t。
#define FlLenInt(v, result) do { \
    CVar __fl_v = (v); \
    if (__fl_v.type_ == VAR_STRING) { \
        (result) = (int64_t)STR_SIZE(__fl_v.data_.s); \
    } else if (__fl_v.type_ == VAR_STRINGID) { \
        (result) = (int64_t)STR_SIZE((VarString *)__fl_v.data_.i); \
    } else if (__fl_v.type_ == VAR_TABLE) { \
        (result) = (int64_t)TABLE_SIZE(__fl_v.data_.t); \
    } else { \
        FakeluaThrowError(_S, "attempt to get length of a non-string/table value"); \
        (result) = 0; \
    } \
} while(0)

)";
}


void CGen::GenerateGlobal(const SyntaxTreeInterfacePtr &chunk) {
    *cur_output_ << "// ===== Global Variables =====\n\n";

    in_global_init_ = true;

    // 静态全局的CVar
    // 定义初始化器宏
    *cur_output_ << "static const CVar kNil = (CVar){.type_ = VAR_NIL};\n";
    *cur_output_ << "static const CVar kTrue = (CVar){.type_ = VAR_BOOL, .data_.b = true};\n";
    *cur_output_ << "static const CVar kFalse = (CVar){.type_ = VAR_BOOL, .data_.b = false};\n";

    // 遍历顶层的 local 变量定义，生成全局常量
    DEBUG_ASSERT(chunk->Type() == SyntaxTreeType::Block);

    for (const auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(chunk); const auto &stmt: block->Stmts()) {
        if (stmt->Type() == SyntaxTreeType::LocalVar) {
            const auto local_var = std::dynamic_pointer_cast<SyntaxTreeLocalVar>(stmt);
            const auto namelist = local_var->Namelist();
            const auto explist = local_var->Explist();

            if (!namelist || !explist) {
                continue;
            }

            DEBUG_ASSERT(namelist->Type() == SyntaxTreeType::NameList);
            DEBUG_ASSERT(explist->Type() == SyntaxTreeType::ExpList);

            const auto namelist_ptr = std::dynamic_pointer_cast<SyntaxTreeNamelist>(namelist);
            const auto explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(explist);
            const auto &names = namelist_ptr->Names();
            auto &exps = explist_ptr->Exps();

            for (size_t i = 0; i < names.size(); ++i) {
                const auto &name = names[i];
                const auto &exp = exps[i];

                // 检查是否重复定义
                if (global_const_vars_.contains(name)) {
                    ThrowError("duplicate global const variable: " + name, stmt);
                }

                // 编译表达式为 CVar 初始化字符串
                std::string cvar_init = func_compiler_.CompileExp(exp);

                // 生成静态全局变量
                *cur_output_ << "static const CVar " << name << " = " << cvar_init << ";\n";

                // 记录变量名
                global_const_vars_.insert(name);
            }
        }
    }

    in_global_init_ = false;

    *cur_output_ << "\n";
}

void CGen::GenerateDecls(const SyntaxTreeInterfacePtr &chunk, GenResult &gr) {
    *cur_output_ << "\n// ===== Function Declarations =====\n\n";

    std::unordered_map<std::string, std::vector<std::string>> func_decls;// 函数名 -> 参数类型列表（用于重载）

    DEBUG_ASSERT(chunk->Type() == SyntaxTreeType::Block);
    for (const auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(chunk); auto &stmt: block->Stmts()) {
        std::string name;
        SyntaxTreeInterfacePtr funcbody;
        if (stmt->Type() == SyntaxTreeType::Function) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeFunction>(stmt);
            name = CompileFuncName(func->Funcname());
            funcbody = func->Funcbody();
        } else if (stmt->Type() == SyntaxTreeType::LocalFunction) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeLocalFunction>(stmt);
            name = func->Name();
            funcbody = func->Funcbody();
        }

        if (!funcbody) {
            continue;
        }

        DEBUG_ASSERT(funcbody->Type() == SyntaxTreeType::FuncBody);
        const auto funcbody_ptr = std::dynamic_pointer_cast<SyntaxTreeFuncbody>(funcbody);
        const auto parlist = funcbody_ptr->Parlist();
        std::vector<std::string> func_params;
        if (parlist) {
            func_params = CompileParList(parlist);
        }
        func_decls[name] = func_params;
    }

    for (const auto &[name, params]: func_decls) {
        // 生成函数声明
        *cur_output_ << "CVar " << name << "(";
        for (size_t i = 0; i < params.size(); ++i) {
            if (i > 0) {
                *cur_output_ << ", ";
            }
            *cur_output_ << "CVar " << params[i];
        }
        *cur_output_ << ");\n";

        // 记录函数参数数量
        gr.function_names[name] = static_cast<int>(params.size());

        // 如果函数含有数学参数，还需声明 2^k 个特化变体。
        const auto math_it = math_param_positions_.find(name);
        if (math_it != math_param_positions_.end()) {
            const auto &math_params = math_it->second;
            const int num_specs = 1 << static_cast<int>(math_params.size());
            for (int bitmask = 0; bitmask < num_specs; ++bitmask) {
                const auto spec_name = SpecFuncName(name, math_params, bitmask);
                const auto spec_ret = func_compiler_.GetSpecReturnType(name, bitmask);
                *cur_output_ << SpecReturnCTypeName(spec_ret) << " " << spec_name << "(";
                for (size_t i = 0; i < params.size(); ++i) {
                    if (i > 0) *cur_output_ << ", ";
                    const auto mp_it = std::ranges::find(math_params, static_cast<int>(i));
                    if (mp_it != math_params.end()) {
                        const int mp_idx = static_cast<int>(mp_it - math_params.begin());
                        *cur_output_ << MathParamCTypeName(MathParamKindOf(bitmask, mp_idx)) << " " << params[i];
                    } else {
                        *cur_output_ << "CVar " << params[i];
                    }
                }
                *cur_output_ << ");\n";
                // 注册特化函数名，使 CompileFunctioncall 能将其识别为
                // 本地调用（同文件直接调用）。
                gr.function_names[spec_name] = static_cast<int>(params.size());
            }
        }
    }

    *cur_output_ << "\n";
}

std::string CGen::CompileFuncName(const SyntaxTreeInterfacePtr &ptr) {
    DEBUG_ASSERT(ptr->Type() == SyntaxTreeType::FuncName);

    const auto name = std::dynamic_pointer_cast<SyntaxTreeFuncname>(ptr);
    const auto funcnamelistptr = name->FuncNameList();

    std::vector<std::string> namelist;

    DEBUG_ASSERT(funcnamelistptr->Type() == SyntaxTreeType::FuncNameList);
    const auto funcnamelist = std::dynamic_pointer_cast<SyntaxTreeFuncnamelist>(funcnamelistptr);
    const auto &names = funcnamelist->Funcnames();
    namelist.insert(namelist.end(), names.begin(), names.end());

    // PreProcessor 已确保函数名为单段
    DEBUG_ASSERT(namelist.size() == 1);

    // PreProcessor 已确保无冒号函数名
    DEBUG_ASSERT(name->ColonName().empty());

    return namelist[0];
}

[[noreturn]] void CGen::ThrowError(const std::string &msg, const SyntaxTreeInterfacePtr &ptr) {
    ThrowFakeluaException(
            std::format("Code generate failed, {} at {}:{}:{}", msg, file_name_, ptr->Loc().begin.line, ptr->Loc().begin.column));
}

bool CGen::BlockEndsWithReturn(const SyntaxTreeInterfacePtr &block) {
    const auto block_ptr = std::dynamic_pointer_cast<SyntaxTreeBlock>(block);
    const auto &stmts = block_ptr->Stmts();
    if (stmts.empty()) {
        return false;
    }
    return stmts.back()->Type() == SyntaxTreeType::Return;
}

std::vector<std::string> CGen::CompileParList(const SyntaxTreeInterfacePtr &parlist) {
    DEBUG_ASSERT(parlist->Type() == SyntaxTreeType::ParList);
    const auto parlist_ptr = std::dynamic_pointer_cast<SyntaxTreeParlist>(parlist);

    // PreProcessor 已确保不存在变长参数
    DEBUG_ASSERT(!parlist_ptr->VarParams());

    if (const auto namelist = parlist_ptr->Namelist()) {
        DEBUG_ASSERT(namelist->Type() == SyntaxTreeType::NameList);
        const auto namelist_ptr = std::dynamic_pointer_cast<SyntaxTreeNamelist>(namelist);
        auto &param_names = namelist_ptr->Names();

        std::set<std::string> param_names_set;
        for (const auto &key: global_const_vars_) {
            param_names_set.insert(key);
        }

        for (auto &name: param_names) {
            if (param_names_set.contains(name)) {
                ThrowError("the param name is duplicated: " + name, namelist_ptr);
            }
            param_names_set.insert(name);
        }

        return param_names;
    }

    return {};
}

void CGen::GenerateImpl(const SyntaxTreeInterfacePtr &chunk, GenResult &gr) {
    DEBUG_ASSERT(chunk->Type() == SyntaxTreeType::Block);
    for (const auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(chunk); auto &stmt: block->Stmts()) {
        std::string name;
        SyntaxTreeInterfacePtr funcbody;
        if (stmt->Type() == SyntaxTreeType::Function) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeFunction>(stmt);
            name = CompileFuncName(func->Funcname());
            funcbody = func->Funcbody();
        } else if (stmt->Type() == SyntaxTreeType::LocalFunction) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeLocalFunction>(stmt);
            name = func->Name();
            funcbody = func->Funcbody();
        }

        if (!funcbody) {
            continue;
        }

        DEBUG_ASSERT(funcbody->Type() == SyntaxTreeType::FuncBody);
        const auto funcbody_ptr = std::dynamic_pointer_cast<SyntaxTreeFuncbody>(funcbody);
        const auto parlist = funcbody_ptr->Parlist();
        std::vector<std::string> func_params;
        if (parlist) {
            func_params = CompileParList(parlist);
        }

        const auto func_block = funcbody_ptr->Block();
        const auto math_it = math_param_positions_.find(name);
        if (math_it != math_param_positions_.end()) {
            // 函数含有数学参数：生成 2^k 个特化函数体，然后生成入口分发器。
            const auto &math_params = math_it->second;
            const int num_specs = 1 << static_cast<int>(math_params.size());
            for (int bitmask = 0; bitmask < num_specs; ++bitmask) {
                const auto spec_name = SpecFuncName(name, math_params, bitmask);
                const auto spec_ret = func_compiler_.GetSpecReturnType(name, bitmask);
                // 输出特化函数签名。
                *cur_output_ << SpecReturnCTypeName(spec_ret) << " " << spec_name << "(";
                for (size_t i = 0; i < func_params.size(); ++i) {
                    if (i > 0) *cur_output_ << ", ";
                    const auto mp_it = std::ranges::find(math_params, static_cast<int>(i));
                    if (mp_it != math_params.end()) {
                        const int mp_idx = static_cast<int>(mp_it - math_params.begin());
                        *cur_output_ << MathParamCTypeName(MathParamKindOf(bitmask, mp_idx)) << " " << func_params[i];
                    } else {
                        *cur_output_ << "CVar " << func_params[i];
                    }
                }
                *cur_output_ << ") {\n";
                CompileFuncBody(name, func_params, func_block, bitmask);
                if (!BlockEndsWithReturn(func_block)) {
                    // 回退：当函数不以 return 结束时补充默认返回值。
                    // 对于原生返回类型，补 0/0.0；对于 CVar 类型，补 kNil。
                    if (spec_ret == T_INT) {
                        *cur_output_ << "    return 0;\n";
                    } else if (spec_ret == T_FLOAT) {
                        *cur_output_ << "    return 0.0;\n";
                    } else {
                        *cur_output_ << "    return kNil;\n";
                    }
                }
                *cur_output_ << "}\n";
            }
            // 输出入口分发器（原始 CVar 签名）。
            GenerateEntryDispatcher(name, func_params, math_params);
        } else {
            // 无数学参数：正常编译（行为不变）。
            *cur_output_ << "CVar " << name << "(";
            for (size_t i = 0; i < func_params.size(); ++i) {
                if (i > 0) *cur_output_ << ", ";
                *cur_output_ << "CVar " << func_params[i];
            }
            *cur_output_ << ") {\n";
            CompileFuncBody(name, func_params, func_block, -1);
            if (!BlockEndsWithReturn(func_block)) {
                *cur_output_ << "    return kNil;\n";
            }
            *cur_output_ << "}\n";
        }
    }
}

void CGen::CompileFuncBody(const std::string &func_name,
                              const std::vector<std::string> &func_params,
                              const SyntaxTreeInterfacePtr &func_block,
                              int spec_bitmask) {
    func_compiler_.CompileFuncBody(func_name, func_params, func_block, spec_bitmask, impls_);
}

void CGen::GenerateEntryDispatcher(const std::string &func_name,
                                    const std::vector<std::string> &func_params,
                                    const std::vector<int> &math_param_indices) {
    const int k = static_cast<int>(math_param_indices.size());
    const int num_specs = 1 << k;

    // 入口函数：始终使用 CVar 签名。
    *cur_output_ << "CVar " << func_name << "(";
    for (size_t i = 0; i < func_params.size(); ++i) {
        if (i > 0) *cur_output_ << ", ";
        *cur_output_ << "CVar " << func_params[i];
    }
    *cur_output_ << ") {\n";

    // 检查 math param 必须是数值类型，否则抛出运行时错误（含参数序号和参数名）。
    for (int i = 0; i < k; ++i) {
        const int param_idx = math_param_indices[i];
        const auto &mp_name = func_params[static_cast<size_t>(param_idx)];
        *cur_output_ << std::format(
                "    if ({0}.type_ != VAR_INT && {0}.type_ != VAR_FLOAT) {{ FakeluaThrowError(_S, \"bad argument #{1} ({2}): attempt to perform arithmetic on non-numeric value\"); }}\n",
                mp_name, param_idx + 1, mp_name);
    }

    // 计算分发索引。
    *cur_output_ << "    int flua_spec_idx = ";
    for (int i = 0; i < k; ++i) {
        if (i > 0) *cur_output_ << " | ";
        const auto &mp_name = func_params[static_cast<size_t>(math_param_indices[i])];
        if (i == 0) {
            *cur_output_ << std::format("({}.type_ == VAR_FLOAT ? {} : {})", mp_name,
                                        static_cast<int>(kMathParamFloat), static_cast<int>(kMathParamInt));
        } else {
            *cur_output_ << std::format("(({}.type_ == VAR_FLOAT ? {} : {}) << {})", mp_name,
                                        static_cast<int>(kMathParamFloat), static_cast<int>(kMathParamInt), i);
        }
    }
    *cur_output_ << ";\n";

    // 分发表（switch）。
    *cur_output_ << "    switch (flua_spec_idx) {\n";
    for (int bitmask = 0; bitmask < num_specs; ++bitmask) {
        const auto spec_name = SpecFuncName(func_name, math_param_indices, bitmask);
        const auto spec_ret = func_compiler_.GetSpecReturnType(func_name, bitmask);

        // 构建参数列表字符串（math 参数取 .data_.i / .data_.f，其余直接传 CVar）。
        std::string args_str;
        for (size_t i = 0; i < func_params.size(); ++i) {
            if (i > 0) {
                args_str += ", ";
            }
            const auto mp_it = std::ranges::find(math_param_indices, static_cast<int>(i));
            if (mp_it != math_param_indices.end()) {
                const int mp_idx = static_cast<int>(mp_it - math_param_indices.begin());
                const auto kind = MathParamKindOf(bitmask, mp_idx);
                args_str += func_params[i] + (kind == kMathParamFloat ? ".data_.f" : ".data_.i");
            } else {
                args_str += func_params[i];
            }
        }

        if (spec_ret == T_INT || spec_ret == T_FLOAT) {
            // 特化函数返回原生数值类型：需要将结果装箱为 CVar 后再返回。
            const auto native_tmp = std::format("flua_r_{}", bitmask);
            *cur_output_ << std::format("        case {}: {{ {} {} = {}({}); return {}; }}\n",
                                        bitmask,
                                        SpecReturnCTypeName(spec_ret),
                                        native_tmp,
                                        spec_name,
                                        args_str,
                                        BoxNativeValue(native_tmp, spec_ret));
        } else {
            *cur_output_ << std::format("        case {}: return {}({});\n", bitmask, spec_name, args_str);
        }
    }
    *cur_output_ << "    }\n";
    *cur_output_ << "    return kNil;\n";
    *cur_output_ << "}\n";
}


}// namespace fakelua
