#include "compile/c_gen.h"
#include "util/common.h"
#include "util/exception.h"
#include "util/file_util.h"

namespace fakelua {

CGen::CGen(State *s) : s_(s) {
}

void CGen::Generate(const CompileResult &cr, const CompileConfig &cfg) {
    LOG_INFO("start CGen::Generate {}", cr.file_name);

    std::string code = Build(cr, cfg);

    auto output_file = cr.file_name + ".c";
    std::ofstream ofs(output_file);
    if (ofs.is_open()) {
        ofs << code;
        ofs.close();
        LOG_INFO("C code generated: {}", output_file);
    } else {
        LOG_ERROR("Failed to open output file: {}", output_file);
    }
}

std::string CGen::Build(const CompileResult &cr, const CompileConfig &cfg) {
    header_.str("");
    header_.clear();
    decl_.str("");
    decl_.clear();
    impl_.str("");
    impl_.clear();
    function_param_counts_.clear();

    GenerateHeader();
    GenerateMacros();

    // 遍历所有函数进行前置声明
    DEBUG_ASSERT(cr.chunk->Type() == SyntaxTreeType::Block);
    auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(cr.chunk);
    for (const auto &stmt: block->Stmts()) {
        if (stmt->Type() == SyntaxTreeType::Function) {
            auto func = std::dynamic_pointer_cast<SyntaxTreeFunction>(stmt);
            auto name = GetFuncName(func->Funcname());
            GenerateDecl(name, func->Funcbody());
        } else if (stmt->Type() == SyntaxTreeType::LocalFunction) {
            auto func = std::dynamic_pointer_cast<SyntaxTreeLocalFunction>(stmt);
            GenerateDecl(func->Name(), func->Funcbody());
        }
    }
    decl_ << "\n";

    // 生成函数实现
    for (const auto &stmt: block->Stmts()) {
        if (stmt->Type() == SyntaxTreeType::Function) {
            auto func = std::dynamic_pointer_cast<SyntaxTreeFunction>(stmt);
            GenerateFunction(GetFuncName(func->Funcname()), func->Funcbody());
        } else if (stmt->Type() == SyntaxTreeType::LocalFunction) {
            auto func = std::dynamic_pointer_cast<SyntaxTreeLocalFunction>(stmt);
            GenerateFunction(func->Name(), func->Funcbody());
        }
    }

    return header_.str() + decl_.str() + impl_.str();
}

void CGen::GenerateHeader() {
    header_ << R"(// Generated by FakeLua CGen
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <assert.h>

typedef struct VarString VarString;
typedef struct VarTable VarTable;
typedef struct State State;

typedef struct CVar {
    int type;
    int flag;
    union {
        bool b;
        int64_t i;
        double f;
        VarString *s;
        VarTable *t;
    } data;
} CVar;

enum {
    VAR_NIL = 0,
    VAR_BOOL = 1,
    VAR_INT = 2,
    VAR_FLOAT = 3,
    VAR_STRING = 4,
    VAR_STRINGID = 5,
    VAR_TABLE = 6,
};

#define SET_NIL(v) do { (v).type = VAR_NIL; } while(0)
#define SET_BOOL(v, val) do { (v).type = VAR_BOOL; (v).data.b = (val); } while(0)
#define SET_INT(v, val) do { (v).type = VAR_INT; (v).data.i = (val); } while(0)
#define SET_FLOAT(v, val) do { (v).type = VAR_FLOAT; (v).data.f = (val); } while(0)

static inline bool is_true(CVar v) { return v.type != VAR_NIL && (v.type != VAR_BOOL || v.data.b); }

)";
}

void CGen::GenerateMacros() {
    header_ << R"(
// Arithmetic operations
static inline CVar op_add(CVar a, CVar b) {
    CVar res;
    if (a.type == VAR_INT && b.type == VAR_INT) { SET_INT(res, a.data.i + b.data.i); }
    else { double f1 = (a.type == VAR_INT) ? (double)a.data.i : a.data.f; double f2 = (b.type == VAR_INT) ? (double)b.data.i : b.data.f; SET_FLOAT(res, f1 + f2); }
    return res;
}
static inline CVar op_sub(CVar a, CVar b) {
    CVar res;
    if (a.type == VAR_INT && b.type == VAR_INT) { SET_INT(res, a.data.i - b.data.i); }
    else { double f1 = (a.type == VAR_INT) ? (double)a.data.i : a.data.f; double f2 = (b.type == VAR_INT) ? (double)b.data.i : b.data.f; SET_FLOAT(res, f1 - f2); }
    return res;
}
static inline CVar op_mul(CVar a, CVar b) {
    CVar res;
    if (a.type == VAR_INT && b.type == VAR_INT) { SET_INT(res, a.data.i * b.data.i); }
    else { double f1 = (a.type == VAR_INT) ? (double)a.data.i : a.data.f; double f2 = (b.type == VAR_INT) ? (double)b.data.i : b.data.f; SET_FLOAT(res, f1 * f2); }
    return res;
}
static inline CVar op_div(CVar a, CVar b) {
    CVar res;
    double f1 = (a.type == VAR_INT) ? (double)a.data.i : a.data.f;
    double f2 = (b.type == VAR_INT) ? (double)b.data.i : b.data.f;
    SET_FLOAT(res, f1 / f2);
    return res;
}

// Comparison operations
static inline CVar op_lt(CVar a, CVar b) {
    CVar res;
    if (a.type == VAR_INT && b.type == VAR_INT) { SET_BOOL(res, a.data.i < b.data.i); }
    else { double f1 = (a.type == VAR_INT) ? (double)a.data.i : a.data.f; double f2 = (b.type == VAR_INT) ? (double)b.data.i : b.data.f; SET_BOOL(res, f1 < f2); }
    return res;
}
static inline CVar op_gt(CVar a, CVar b) {
    CVar res;
    if (a.type == VAR_INT && b.type == VAR_INT) { SET_BOOL(res, a.data.i > b.data.i); }
    else { double f1 = (a.type == VAR_INT) ? (double)a.data.i : a.data.f; double f2 = (b.type == VAR_INT) ? (double)b.data.i : b.data.f; SET_BOOL(res, f1 > f2); }
    return res;
}
static inline CVar op_eq(CVar a, CVar b) {
    CVar res;
    if (a.type != b.type) { SET_BOOL(res, false); }
    else if (a.type == VAR_INT) { SET_BOOL(res, a.data.i == b.data.i); }
    else if (a.type == VAR_FLOAT) { SET_BOOL(res, a.data.f == b.data.f); }
    else if (a.type == VAR_BOOL) { SET_BOOL(res, a.data.b == b.data.b); }
    else { SET_BOOL(res, false); } // TODO: string/table
    return res;
}

static inline CVar op_not(CVar a) { CVar res; SET_BOOL(res, !is_true(a)); return res; }

// Placeholders for Table and String
static inline CVar fl_get_table(State *s, CVar t, CVar k) { return (CVar){VAR_NIL}; }
static inline void fl_set_table(State *s, CVar t, CVar k, CVar v) { }
static inline CVar fl_concat(State *s, CVar a, CVar b) { return (CVar){VAR_NIL}; }

)";
}

std::string CGen::GetFuncName(const SyntaxTreeInterfacePtr &ptr) {
    auto name_node = std::dynamic_pointer_cast<SyntaxTreeFuncname>(ptr);
    auto list = std::dynamic_pointer_cast<SyntaxTreeFuncnamelist>(name_node->FuncNameList());
    return list->Funcnames()[0];
}

void CGen::GenerateDecl(const std::string &name, const SyntaxTreeInterfacePtr &body) {
    auto funcbody = std::dynamic_pointer_cast<SyntaxTreeFuncbody>(body);
    decl_ << "static CVar " << name << "(State *s";
    auto parlist = std::dynamic_pointer_cast<SyntaxTreeParlist>(funcbody->Parlist());
    if (parlist && parlist->Namelist()) {
        auto names = std::dynamic_pointer_cast<SyntaxTreeNamelist>(parlist->Namelist())->Names();
        for (const auto &pname: names) {
            decl_ << ", CVar " << pname;
        }
    }
    decl_ << ");\n";
    function_param_counts_[name] =
            (parlist && parlist->Namelist()) ? std::dynamic_pointer_cast<SyntaxTreeNamelist>(parlist->Namelist())->Names().size() : 0;
}

void CGen::GenerateFunction(const std::string &name, const SyntaxTreeInterfacePtr &body) {
    auto funcbody = std::dynamic_pointer_cast<SyntaxTreeFuncbody>(body);
    impl_ << "static CVar " << name << "(State *s";

    auto parlist = std::dynamic_pointer_cast<SyntaxTreeParlist>(funcbody->Parlist());
    if (parlist && parlist->Namelist()) {
        auto names = std::dynamic_pointer_cast<SyntaxTreeNamelist>(parlist->Namelist())->Names();
        for (const auto &pname: names) {
            impl_ << ", CVar " << pname;
        }
    }
    impl_ << ") {\n";

    std::set<std::string> locals;
    CollectLocals(funcbody->Block(), locals);
    if (parlist && parlist->Namelist()) {
        auto names = std::dynamic_pointer_cast<SyntaxTreeNamelist>(parlist->Namelist())->Names();
        for (const auto &pname: names) locals.erase(pname);
    }
    for (const auto &lname: locals) {
        impl_ << "    CVar " << lname << " = {VAR_NIL};\n";
    }

    GenerateBlock(funcbody->Block(), 1);

    impl_ << "    return (CVar){VAR_NIL};\n";
    impl_ << "}\n\n";
}

void CGen::CollectLocals(const SyntaxTreeInterfacePtr &node, std::set<std::string> &locals) {
    if (!node) return;
    WalkSyntaxTree(node, [&](const SyntaxTreeInterfacePtr &ptr) {
        if (ptr->Type() == SyntaxTreeType::LocalVar) {
            auto lv = std::dynamic_pointer_cast<SyntaxTreeLocalVar>(ptr);
            auto names = std::dynamic_pointer_cast<SyntaxTreeNamelist>(lv->Namelist())->Names();
            for (const auto &n: names) locals.insert(n);
        }
    });
}

void CGen::GenerateBlock(const SyntaxTreeInterfacePtr &node, int indent) {
    auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(node);
    for (const auto &stmt: block->Stmts()) {
        GenerateStmt(stmt, indent);
    }
}

void CGen::GenerateStmt(const SyntaxTreeInterfacePtr &stmt, int indent) {
    std::string tabs(indent * 4, ' ');
    switch (stmt->Type()) {
        case SyntaxTreeType::Assign: {
            auto assign = std::dynamic_pointer_cast<SyntaxTreeAssign>(stmt);
            auto var = std::dynamic_pointer_cast<SyntaxTreeVar>(std::dynamic_pointer_cast<SyntaxTreeVarlist>(assign->Varlist())->Vars()[0]);
            auto exp = std::dynamic_pointer_cast<SyntaxTreeExplist>(assign->Explist())->Exps()[0];
            if (var->GetType() == "simple") {
                impl_ << tabs << var->GetName() << " = ";
                GenerateExp(exp);
                impl_ << ";\n";
            } else {
                impl_ << tabs << "fl_set_table(s, ";
                GeneratePrefixexp(var->GetPrefixexp());
                impl_ << ", ";
                if (var->GetType() == "dot") impl_ << "/* TODO: string k */";
                else
                    GenerateExp(var->GetExp());
                impl_ << ", ";
                GenerateExp(exp);
                impl_ << ");\n";
            }
            break;
        }
        case SyntaxTreeType::LocalVar: {
            auto lv = std::dynamic_pointer_cast<SyntaxTreeLocalVar>(stmt);
            auto names = std::dynamic_pointer_cast<SyntaxTreeNamelist>(lv->Namelist())->Names();
            if (lv->Explist()) {
                auto exps = std::dynamic_pointer_cast<SyntaxTreeExplist>(lv->Explist())->Exps();
                for (size_t i = 0; i < names.size() && i < exps.size(); ++i) {
                    impl_ << tabs << names[i] << " = ";
                    GenerateExp(exps[i]);
                    impl_ << ";\n";
                }
            }
            break;
        }
        case SyntaxTreeType::Return: {
            auto ret = std::dynamic_pointer_cast<SyntaxTreeReturn>(stmt);
            impl_ << tabs << "return ";
            if (ret->Explist() && !std::dynamic_pointer_cast<SyntaxTreeExplist>(ret->Explist())->Exps().empty()) {
                GenerateExp(std::dynamic_pointer_cast<SyntaxTreeExplist>(ret->Explist())->Exps()[0]);
            } else {
                impl_ << "(CVar){VAR_NIL}";
            }
            impl_ << ";\n";
            break;
        }
        case SyntaxTreeType::If: {
            auto if_stmt = std::dynamic_pointer_cast<SyntaxTreeIf>(stmt);
            impl_ << tabs << "if (is_true(";
            GenerateExp(if_stmt->Exp());
            impl_ << ")) {\n";
            GenerateBlock(if_stmt->Block(), indent + 1);

            if (if_stmt->ElseIfs()) {
                auto elseifs = std::dynamic_pointer_cast<SyntaxTreeElseiflist>(if_stmt->ElseIfs());
                for (size_t i = 0; i < elseifs->ElseifSize(); ++i) {
                    impl_ << tabs << "} else if (is_true(";
                    GenerateExp(elseifs->ElseifExp(i));
                    impl_ << ")) {\n";
                    GenerateBlock(elseifs->ElseifBlock(i), indent + 1);
                }
            }

            if (if_stmt->ElseBlock()) {
                impl_ << tabs << "} else {\n";
                GenerateBlock(if_stmt->ElseBlock(), indent + 1);
            }

            impl_ << tabs << "}\n";
            break;
        }
        case SyntaxTreeType::While: {
            auto while_stmt = std::dynamic_pointer_cast<SyntaxTreeWhile>(stmt);
            impl_ << tabs << "while (is_true(";
            GenerateExp(while_stmt->Exp());
            impl_ << ")) {\n";
            GenerateBlock(while_stmt->Block(), indent + 1);
            impl_ << tabs << "}\n";
            break;
        }
        default:
            impl_ << tabs << "// Unsupported statement type: " << SyntaxTreeTypeToString(stmt->Type()) << "\n";
            break;
    }
}

void CGen::GenerateExp(const SyntaxTreeInterfacePtr &node) {
    auto exp = std::dynamic_pointer_cast<SyntaxTreeExp>(node);
    const auto &type = exp->ExpType();
    if (type == "number") {
        if (exp->ExpValue().find('.') != std::string::npos) {
            impl_ << "((CVar){VAR_FLOAT, 0, {.f = " << exp->ExpValue() << "}})";
        } else {
            impl_ << "((CVar){VAR_INT, 0, {.i = " << exp->ExpValue() << "}})";
        }
    } else if (type == "nil") {
        impl_ << "((CVar){VAR_NIL})";
    } else if (type == "true") {
        impl_ << "((CVar){VAR_BOOL, 0, {.b = true}})";
    } else if (type == "false") {
        impl_ << "((CVar){VAR_BOOL, 0, {.b = false}})";
    } else if (type == "string") {
        impl_ << "/* TODO: string */ (CVar){VAR_NIL}";
    } else if (type == "prefixexp") {
        GeneratePrefixexp(exp->Right());
    } else if (type == "binop") {
        auto op = std::dynamic_pointer_cast<SyntaxTreeBinop>(exp->Op())->GetOp();
        std::string func;
        if (op == "PLUS") func = "op_add";
        else if (op == "MINUS")
            func = "op_sub";
        else if (op == "STAR")
            func = "op_mul";
        else if (op == "SLASH")
            func = "op_div";
        else if (op == "LESS")
            func = "op_lt";
        else if (op == "MORE")
            func = "op_gt";
        else if (op == "EQUAL")
            func = "op_eq";

        if (!func.empty()) {
            impl_ << func << "(";
            GenerateExp(exp->Left());
            impl_ << ", ";
            GenerateExp(exp->Right());
            impl_ << ")";
        }
    } else if (type == "unop") {
        auto op = std::dynamic_pointer_cast<SyntaxTreeUnop>(exp->Op())->GetOp();
        if (op == "NOT") {
            impl_ << "op_not(";
            GenerateExp(exp->Right());
            impl_ << ")";
        }
    }
}

void CGen::GeneratePrefixexp(const SyntaxTreeInterfacePtr &node) {
    auto pe = std::dynamic_pointer_cast<SyntaxTreePrefixexp>(node);
    if (pe->GetType() == "var") {
        auto var = std::dynamic_pointer_cast<SyntaxTreeVar>(pe->GetValue());
        if (var->GetType() == "simple") {
            impl_ << var->GetName();
        } else {
            impl_ << "fl_get_table(s, ";
            GeneratePrefixexp(var->GetPrefixexp());
            impl_ << ", ";
            if (var->GetType() == "dot") impl_ << "/* TODO: string k */";
            else
                GenerateExp(var->GetExp());
            impl_ << ")";
        }
    } else if (pe->GetType() == "functioncall") {
        auto fc = std::dynamic_pointer_cast<SyntaxTreeFunctioncall>(pe->GetValue());
        auto fname = GetFuncName(fc->prefixexp());
        impl_ << fname << "(s";
        auto args = std::dynamic_pointer_cast<SyntaxTreeArgs>(fc->Args());
        if (args->GetType() == "explist") {
            auto exps = std::dynamic_pointer_cast<SyntaxTreeExplist>(args->Explist())->Exps();
            for (auto &e: exps) {
                impl_ << ", ";
                GenerateExp(e);
            }
            size_t provided = exps.size();
            size_t total = function_param_counts_[fname];
            for (size_t i = provided; i < total; ++i) {
                impl_ << ", (CVar){VAR_NIL}";
            }
        }
        impl_ << ")";
    } else if (pe->GetType() == "exp") {
        impl_ << "(";
        GenerateExp(pe->GetValue());
        impl_ << ")";
    }
}

}// namespace fakelua
