#include "compile/c_gen.h"

#include "state/state.h"
#include "util/common.h"
#include "util/exception.h"
#include "util/file_util.h"

namespace fakelua {

CGen::CGen(State *s) : s_(s) {
}

void CGen::Generate(CompileResult &cr, const CompileConfig &cfg) {
    LOG_INFO("start CGen::Generate {}", cr.file_name);

    file_name_ = cr.file_name;

    // 生成代码
    const std::string code = Build(cr, cfg);

    if (cfg.debug_mode) {
        const auto dumpfile = GenerateTmpFilename("fakelua_jit_", ".c");
        if (std::ofstream ofs(dumpfile); ofs.is_open()) {
            ofs << code;
            ofs.close();
            std::cerr << "CGen::Generate: C code dumped to " << dumpfile << std::endl;
            LOG_INFO("C code generated: {}", dumpfile);
        } else {
            LOG_ERROR("Failed to open output file: {}", dumpfile);
        }
    }

    cr.c_code = code;

    LOG_INFO("end CGen::Generate {}, functions: {}", cr.file_name, cr.function_names.size());
}

std::string CGen::Build(CompileResult &cr, const CompileConfig &cfg) {
    cur_output_ = &headers_;
    GenerateHeader();
    cur_output_ = &globals_;
    GenerateGlobal(cr);
    cur_output_ = &decls_;
    GenerateDecls(cr);
    local_func_names_ = cr.function_names;
    cur_output_ = &impls_;
    GenerateImpl(cr);
    return headers_.str() + globals_.str() + decls_.str() + impls_.str();
}

void CGen::GenerateHeader() {
    *cur_output_ << R"(// Generated by FakeLua CGen
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <stdlib.h>
#include <stdio.h>

)";

    // 硬编码state指针
    *cur_output_ << "static void * _S = (void *) " << s_ << ";\n";

    *cur_output_ << R"(
typedef struct VarString {
    int size_;
    uint32_t hash_;
    char data_[0];
} VarString;

typedef struct VarTable VarTable;

typedef struct CVar {
    int type_;
    int flag_;
    union {
        bool b;
        int64_t i;
        double f;
        VarString *s;
        VarTable *t;
    } data_;
} CVar;

// 编译期断言：确保 CVar 大小为 16 字节
typedef char check_cvar_size[sizeof(CVar) == 16 ? 1 : -1];

typedef struct VarEntry {
    CVar key;
    CVar val;
    uint32_t hash;
} VarEntry;

typedef struct TableNode {
    VarEntry entry;
    uint32_t next;
    uint32_t active_pos;
} TableNode;

struct VarTable {
    uint32_t count_;
    uint32_t bucket_count_;
    TableNode *nodes_;
    uint32_t *active_list_;
    VarEntry quick_data_[8];
    uint32_t free_list_idx_;
};

typedef struct State State;

#define STR_SIZE(s) ((s)->size_)
#define STR_DATA(s) ((s)->data_)
#define TABLE_SIZE(t) ((t)->count_)

enum {
    VAR_NIL = 0,
    VAR_BOOL = 1,
    VAR_INT = 2,
    VAR_FLOAT = 3,
    VAR_STRING = 4,
    VAR_STRINGID = 5,
    VAR_TABLE = 6,
};

#define SET_NIL(v) do { (v).type_ = VAR_NIL; } while(0)
#define SET_BOOL(v, val) do { (v).type_ = VAR_BOOL; (v).data_.b = (val); } while(0)
#define SET_INT(v, val) do { (v).type_ = VAR_INT; (v).data_.i = (val); } while(0)
#define SET_FLOAT(v, val) do { \
    double __f = (val); \
    (v).type_ = VAR_FLOAT; \
    (v).data_.f = __f; \
} while(0)

// Normalize table keys to match Lua behavior:
// integral float keys are treated as integer keys (e.g. t[2.0] == t[2]).
#define NORMALIZE_TABLE_KEY(key) ({ \
    CVar __k = (key); \
    if (__k.type_ == VAR_FLOAT) { \
        double __d = __k.data_.f; \
        if (isfinite(__d)) { \
            double __ip; \
            if (modf(__d, &__ip) == 0.0 && __ip >= (double)INT64_MIN && __ip <= (double)INT64_MAX) { \
                __k.type_ = VAR_INT; \
                __k.data_.i = (int64_t)__ip; \
            } \
        } \
    } \
    __k; \
})

// External functions for allocation and error handling
extern void* FakeluaAllocTemp(State *s, size_t size);
extern void FakeluaThrowError(State *s, const char *msg);
extern CVar FakeluaCallByName(State *s, int jit_type, const char *name, int arg_num, ...);

#ifndef FAKELUA_JIT_TYPE
#define FAKELUA_JIT_TYPE 0
#endif

static inline uint32_t FlHashString(const char *str, int len) {
    uint32_t hash = 5381;
    int i;
    for (i = 0; i < len; ++i) {
        hash = ((hash << 5) + hash) + (uint8_t)str[i];
    }
    if (hash == 0) {
        hash = 1;
    }
    return hash;
}

#define SET_STRING(v, str, len) do { \
    int __len = (len); \
    const char *__s_ptr = (str); \
    VarString *__vs = (VarString *)FakeluaAllocTemp(_S, sizeof(VarString) + __len); \
    __vs->size_ = __len; \
    __vs->hash_ = 0; \
    memcpy(__vs->data_, __s_ptr, __len); \
    (v).type_ = VAR_STRING; \
    (v).data_.s = __vs; \
} while(0)

#define SET_TABLE(v) do { \
    VarTable *__t = (VarTable *)FakeluaAllocTemp(_S, sizeof(VarTable)); \
    __t->count_ = 0; \
    __t->bucket_count_ = 0; \
    __t->nodes_ = NULL; \
    __t->active_list_ = NULL; \
    __t->free_list_idx_ = 0xFFFFFFFF; \
    assert(sizeof(__t->quick_data_) == 8 * sizeof(VarEntry)); \
    { int __i; for (__i = 0; __i < 8; ++__i) { \
        __t->quick_data_[__i].key.type_ = VAR_NIL; \
        __t->quick_data_[__i].val.type_ = VAR_NIL; \
        __t->quick_data_[__i].hash = 0; \
    } } \
    (v).type_ = VAR_TABLE; \
    (v).data_.t = __t; \
} while(0)

// Logical and Equality macros
#define IsTrue(v, result) do { \
    CVar __tv = (v); \
    (result) = (__tv.type_ != VAR_NIL && (__tv.type_ != VAR_BOOL || __tv.data_.b)); \
} while(0)

#define VarEqual(_fa, _fb, result) do { \
    CVar __a = (_fa), __b = (_fb); \
    if (__a.type_ != __b.type_) { \
        if ((__a.type_ == VAR_STRING || __a.type_ == VAR_STRINGID) && \
            (__b.type_ == VAR_STRING || __b.type_ == VAR_STRINGID)) { \
            VarString *__sa = (__a.type_ == VAR_STRING) ? __a.data_.s : (VarString *)__a.data_.i; \
            VarString *__sb = (__b.type_ == VAR_STRING) ? __b.data_.s : (VarString *)__b.data_.i; \
            if (__sa == __sb) { (result) = true; break; } \
            (result) = (__sa->size_ == __sb->size_ && memcmp(__sa->data_, __sb->data_, __sa->size_) == 0); \
        } else { \
            (result) = false; \
        } \
        break; \
    } \
    switch (__a.type_) { \
        case VAR_NIL: (result) = true; break; \
        case VAR_BOOL: (result) = (__a.data_.b == __b.data_.b); break; \
        case VAR_INT: (result) = (__a.data_.i == __b.data_.i); break; \
        case VAR_FLOAT: (result) = (__a.data_.f == __b.data_.f); break; \
        case VAR_STRING: { \
            if (__a.data_.s == __b.data_.s) { (result) = true; break; } \
            (result) = (__a.data_.s->size_ == __b.data_.s->size_ && memcmp(__a.data_.s->data_, __b.data_.s->data_, __a.data_.s->size_) == 0); \
            break; \
        } \
        case VAR_STRINGID: (result) = (__a.data_.i == __b.data_.i); break; \
        case VAR_TABLE: (result) = (__a.data_.t == __b.data_.t); break; \
        default: (result) = false; break; \
    } \
} while(0)

#define VarHash(v, hash) do { \
    CVar __v = (v); \
    switch (__v.type_) { \
        case VAR_NIL: (hash) = 0; break; \
        case VAR_BOOL: (hash) = (__v.data_.b ? 1 : 0); break; \
        case VAR_INT: (hash) = (uint32_t)(__v.data_.i ^ (__v.data_.i >> 32)); break; \
        case VAR_FLOAT: { union { double __d; uint64_t __u; } __fu; __fu.__d = __v.data_.f; (hash) = (uint32_t)(__fu.__u ^ (__fu.__u >> 32)); break; } \
        case VAR_STRING: { if (__v.data_.s->hash_ == 0) { __v.data_.s->hash_ = FlHashString(__v.data_.s->data_, __v.data_.s->size_); } (hash) = __v.data_.s->hash_; break; } \
        case VAR_STRINGID: { VarString *__vs = (VarString *)__v.data_.i; if (__vs->hash_ == 0) { __vs->hash_ = FlHashString(__vs->data_, __vs->size_); } (hash) = __vs->hash_; break; } \
        case VAR_TABLE: (hash) = (uint32_t)((uintptr_t)__v.data_.t ^ ((uintptr_t)__v.data_.t >> 32)); break; \
        default: (hash) = 0; break; \
    } \
} while(0)

static inline CVar FlGetTable(CVar t, CVar k) {
    k = NORMALIZE_TABLE_KEY(k);
    if (t.type_ != VAR_TABLE) { return (CVar){VAR_NIL}; }
    if (k.type_ == VAR_NIL) { FakeluaThrowError(_S, "table index is nil"); }
    VarTable *tbl = t.data_.t;
    if (tbl->count_ == 0) { return (CVar){VAR_NIL}; }
    uint32_t h; VarHash(k, h);
    if (tbl->bucket_count_ == 0) {
        bool __eq;
        if (tbl->quick_data_[0].hash == h) { VarEqual(tbl->quick_data_[0].key, k, __eq); if (__eq) { return tbl->quick_data_[0].val; } }
        if (tbl->count_ > 1 && tbl->quick_data_[1].hash == h) { VarEqual(tbl->quick_data_[1].key, k, __eq); if (__eq) { return tbl->quick_data_[1].val; } }
        if (tbl->count_ > 2 && tbl->quick_data_[2].hash == h) { VarEqual(tbl->quick_data_[2].key, k, __eq); if (__eq) { return tbl->quick_data_[2].val; } }
        if (tbl->count_ > 3 && tbl->quick_data_[3].hash == h) { VarEqual(tbl->quick_data_[3].key, k, __eq); if (__eq) { return tbl->quick_data_[3].val; } }
        if (tbl->count_ > 4 && tbl->quick_data_[4].hash == h) { VarEqual(tbl->quick_data_[4].key, k, __eq); if (__eq) { return tbl->quick_data_[4].val; } }
        if (tbl->count_ > 5 && tbl->quick_data_[5].hash == h) { VarEqual(tbl->quick_data_[5].key, k, __eq); if (__eq) { return tbl->quick_data_[5].val; } }
        if (tbl->count_ > 6 && tbl->quick_data_[6].hash == h) { VarEqual(tbl->quick_data_[6].key, k, __eq); if (__eq) { return tbl->quick_data_[6].val; } }
        if (tbl->count_ > 7 && tbl->quick_data_[7].hash == h) { VarEqual(tbl->quick_data_[7].key, k, __eq); if (__eq) { return tbl->quick_data_[7].val; } }
    } else {
        uint32_t mask = tbl->bucket_count_ - 1;
        uint32_t idx = h & mask;
        TableNode *curr = &tbl->nodes_[idx];
        if (curr->entry.key.type_ == VAR_NIL) { return (CVar){VAR_NIL}; }
        while (1) {
            if (curr->entry.hash == h) { bool __eq; VarEqual(curr->entry.key, k, __eq); if (__eq) { return curr->entry.val; } }
            uint32_t next = curr->next;
            if (next == 0xFFFFFFFF) { break; }
            curr = &tbl->nodes_[next];
        }
    }
    return (CVar){VAR_NIL};
}

static inline uint32_t NextPowerOfTwo(uint32_t v) {
    v--; v |= v >> 1; v |= v >> 2; v |= v >> 4; v |= v >> 8; v |= v >> 16; v++;
    return v;
}

static inline bool FlTableInsertRaw(VarTable *tbl, CVar key, CVar val, uint32_t hash) {
    uint32_t mask = tbl->bucket_count_ - 1;
    uint32_t total_nodes = tbl->bucket_count_ + tbl->bucket_count_ / 2;
    assert(tbl->count_ < total_nodes);
    uint32_t idx = hash & mask;
    TableNode *main_node = &tbl->nodes_[idx];
    if (main_node->entry.key.type_ == VAR_NIL) {
        main_node->entry.key = key; main_node->entry.val = val; main_node->entry.hash = hash; main_node->next = 0xFFFFFFFF;
        main_node->active_pos = tbl->count_; tbl->active_list_[tbl->count_] = idx;
        tbl->count_++; return true;
    }
    uint32_t curr_idx = idx;
    while (1) {
        TableNode *curr = &tbl->nodes_[curr_idx];
        if (curr->entry.hash == hash) { bool __eq; VarEqual(curr->entry.key, key, __eq); if (__eq) { curr->entry.val = val; return true; } }
        if (curr->next == 0xFFFFFFFF) { break; }
        curr_idx = curr->next;
    }
    if (tbl->free_list_idx_ == 0xFFFFFFFF) { return false; }
    uint32_t new_node_idx = tbl->free_list_idx_;
    TableNode *new_node = &tbl->nodes_[new_node_idx];
    tbl->free_list_idx_ = new_node->next;
    new_node->entry.key = key; new_node->entry.val = val; new_node->entry.hash = hash;
    new_node->next = main_node->next; main_node->next = new_node_idx;
    new_node->active_pos = tbl->count_; tbl->active_list_[tbl->count_] = new_node_idx;
    tbl->count_++; return true;
}

static inline void FlTableRehash(VarTable *tbl) {
    uint32_t old_count = tbl->count_;
    uint32_t old_bucket_count = tbl->bucket_count_;
    TableNode *old_nodes = tbl->nodes_;
    uint32_t new_bucket_count = NextPowerOfTwo(old_count + 1);
    if (new_bucket_count <= old_bucket_count) { new_bucket_count = old_bucket_count * 2; }
    while (1) {
        uint32_t overflow_count = new_bucket_count / 2;
        uint32_t total_nodes = new_bucket_count + overflow_count;
        size_t nodes_size = total_nodes * sizeof(TableNode);
        size_t active_list_size = total_nodes * sizeof(uint32_t);
        char *buffer = (char *)FakeluaAllocTemp(_S, nodes_size + active_list_size);
        TableNode *new_nodes = (TableNode *)buffer;
        uint32_t *new_active_list = (uint32_t *)(buffer + nodes_size);
        { uint32_t i; for (i = 0; i < total_nodes; ++i) { new_nodes[i].entry.key.type_ = VAR_NIL; new_nodes[i].next = 0xFFFFFFFF; new_nodes[i].active_pos = 0xFFFFFFFF; } }
        TableNode *prev_nodes = tbl->nodes_; uint32_t *prev_active_list = tbl->active_list_; uint32_t prev_bucket_count = tbl->bucket_count_; uint32_t prev_count = tbl->count_; uint32_t prev_free_list_idx = tbl->free_list_idx_;
        tbl->nodes_ = new_nodes; tbl->active_list_ = new_active_list; tbl->bucket_count_ = new_bucket_count; tbl->count_ = 0;
        if (overflow_count > 0) {
            { uint32_t i; for (i = 0; i < overflow_count - 1; ++i) { tbl->nodes_[new_bucket_count + i].next = new_bucket_count + i + 1; } }
            tbl->nodes_[new_bucket_count + overflow_count - 1].next = 0xFFFFFFFF;
            tbl->free_list_idx_ = new_bucket_count;
        } else {
            tbl->free_list_idx_ = 0xFFFFFFFF;
        }
        bool success = true;
        if (old_bucket_count == 0) {
            { uint32_t i; for (i = 0; i < old_count; ++i) { if (!FlTableInsertRaw(tbl, tbl->quick_data_[i].key, tbl->quick_data_[i].val, tbl->quick_data_[i].hash)) { success = false; break; } } }
        } else {
            { uint32_t i; for (i = 0; i < old_bucket_count; ++i) {
                uint32_t curr_idx = i;
                while (curr_idx != 0xFFFFFFFF) {
                    TableNode *old_node = &old_nodes[curr_idx];
                    if (old_node->entry.key.type_ != VAR_NIL) { if (!FlTableInsertRaw(tbl, old_node->entry.key, old_node->entry.val, old_node->entry.hash)) { success = false; break; } }
                    curr_idx = old_node->next;
                }
                if (!success) { break; }
            } }
        }
        if (success) { break; } else { tbl->nodes_ = prev_nodes; tbl->active_list_ = prev_active_list; tbl->bucket_count_ = prev_bucket_count; tbl->count_ = prev_count; tbl->free_list_idx_ = prev_free_list_idx; new_bucket_count *= 2; }
    }
}

static inline void FlSetTable(CVar t, CVar k, CVar v) {
    k = NORMALIZE_TABLE_KEY(k);
    if (t.type_ != VAR_TABLE) { return; }
    if (k.type_ == VAR_NIL) { FakeluaThrowError(_S, "table index is nil"); }
    VarTable *tbl = t.data_.t; uint32_t h; VarHash(k, h);
    if (v.type_ == VAR_NIL) {
        if (tbl->count_ == 0) { return; }
        if (tbl->bucket_count_ == 0) {
            bool __eq;
            if (tbl->quick_data_[0].hash == h) { VarEqual(tbl->quick_data_[0].key, k, __eq); if (__eq) { if (tbl->count_ > 1) { tbl->quick_data_[0] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 1 && tbl->quick_data_[1].hash == h) { VarEqual(tbl->quick_data_[1].key, k, __eq); if (__eq) { if (tbl->count_ > 2) { tbl->quick_data_[1] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 2 && tbl->quick_data_[2].hash == h) { VarEqual(tbl->quick_data_[2].key, k, __eq); if (__eq) { if (tbl->count_ > 3) { tbl->quick_data_[2] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 3 && tbl->quick_data_[3].hash == h) { VarEqual(tbl->quick_data_[3].key, k, __eq); if (__eq) { if (tbl->count_ > 4) { tbl->quick_data_[3] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 4 && tbl->quick_data_[4].hash == h) { VarEqual(tbl->quick_data_[4].key, k, __eq); if (__eq) { if (tbl->count_ > 5) { tbl->quick_data_[4] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 5 && tbl->quick_data_[5].hash == h) { VarEqual(tbl->quick_data_[5].key, k, __eq); if (__eq) { if (tbl->count_ > 6) { tbl->quick_data_[5] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 6 && tbl->quick_data_[6].hash == h) { VarEqual(tbl->quick_data_[6].key, k, __eq); if (__eq) { if (tbl->count_ > 7) { tbl->quick_data_[6] = tbl->quick_data_[tbl->count_ - 1]; } tbl->count_--; return; } }
            if (tbl->count_ > 7 && tbl->quick_data_[7].hash == h) { VarEqual(tbl->quick_data_[7].key, k, __eq); if (__eq) { tbl->count_--; return; } }
        } else {
            uint32_t mask = tbl->bucket_count_ - 1; uint32_t idx = h & mask; TableNode *curr = &tbl->nodes_[idx];
            if (curr->entry.key.type_ == VAR_NIL) { return; }
            { bool __eq; VarEqual(curr->entry.key, k, __eq); if (curr->entry.hash == h && __eq) {
                if (curr->next != 0xFFFFFFFF) {
                    uint32_t next_idx = curr->next; TableNode *next_node = &tbl->nodes_[next_idx];
                    uint32_t pos = next_node->active_pos; uint32_t last_node_idx = tbl->active_list_[tbl->count_ - 1];
                    if (next_idx != last_node_idx) { tbl->active_list_[pos] = last_node_idx; tbl->nodes_[last_node_idx].active_pos = pos; }
                    next_node->active_pos = 0xFFFFFFFF; curr->entry = next_node->entry; curr->next = next_node->next; next_node->next = tbl->free_list_idx_; tbl->free_list_idx_ = next_idx;
                } else {
                    uint32_t pos = curr->active_pos; uint32_t last_node_idx = tbl->active_list_[tbl->count_ - 1];
                    if (idx != last_node_idx) { tbl->active_list_[pos] = last_node_idx; tbl->nodes_[last_node_idx].active_pos = pos; }
                    curr->active_pos = 0xFFFFFFFF; curr->entry.key.type_ = VAR_NIL;
                }
                tbl->count_--; return;
            } }
            uint32_t prev_idx = idx; uint32_t curr_idx = curr->next;
            while (curr_idx != 0xFFFFFFFF) {
                TableNode *node = &tbl->nodes_[curr_idx];
                { bool __eq; VarEqual(node->entry.key, k, __eq); if (node->entry.hash == h && __eq) {
                    uint32_t pos = node->active_pos; uint32_t last_node_idx = tbl->active_list_[tbl->count_ - 1];
                    if (curr_idx != last_node_idx) { tbl->active_list_[pos] = last_node_idx; tbl->nodes_[last_node_idx].active_pos = pos; }
                    node->active_pos = 0xFFFFFFFF; tbl->nodes_[prev_idx].next = node->next; node->next = tbl->free_list_idx_; tbl->free_list_idx_ = curr_idx; tbl->count_--; return;
                } }
                prev_idx = curr_idx; curr_idx = node->next;
            }
        }
        return;
    }
    if (tbl->bucket_count_ == 0) {
        bool __eq;
        if (tbl->count_ > 0 && tbl->quick_data_[0].hash == h) { VarEqual(tbl->quick_data_[0].key, k, __eq); if (__eq) { tbl->quick_data_[0].val = v; return; } }
        if (tbl->count_ > 1 && tbl->quick_data_[1].hash == h) { VarEqual(tbl->quick_data_[1].key, k, __eq); if (__eq) { tbl->quick_data_[1].val = v; return; } }
        if (tbl->count_ > 2 && tbl->quick_data_[2].hash == h) { VarEqual(tbl->quick_data_[2].key, k, __eq); if (__eq) { tbl->quick_data_[2].val = v; return; } }
        if (tbl->count_ > 3 && tbl->quick_data_[3].hash == h) { VarEqual(tbl->quick_data_[3].key, k, __eq); if (__eq) { tbl->quick_data_[3].val = v; return; } }
        if (tbl->count_ > 4 && tbl->quick_data_[4].hash == h) { VarEqual(tbl->quick_data_[4].key, k, __eq); if (__eq) { tbl->quick_data_[4].val = v; return; } }
        if (tbl->count_ > 5 && tbl->quick_data_[5].hash == h) { VarEqual(tbl->quick_data_[5].key, k, __eq); if (__eq) { tbl->quick_data_[5].val = v; return; } }
        if (tbl->count_ > 6 && tbl->quick_data_[6].hash == h) { VarEqual(tbl->quick_data_[6].key, k, __eq); if (__eq) { tbl->quick_data_[6].val = v; return; } }
        if (tbl->count_ > 7 && tbl->quick_data_[7].hash == h) { VarEqual(tbl->quick_data_[7].key, k, __eq); if (__eq) { tbl->quick_data_[7].val = v; return; } }
        if (tbl->count_ < 8) { tbl->quick_data_[tbl->count_].key = k; tbl->quick_data_[tbl->count_].val = v; tbl->quick_data_[tbl->count_].hash = h; tbl->count_++; return; }
        FlTableRehash(tbl);
    }
    if (tbl->count_ >= tbl->bucket_count_ || tbl->free_list_idx_ == 0xFFFFFFFF) { FlTableRehash(tbl); }
    FlTableInsertRaw(tbl, k, v, h);
}

// Arithmetic and Comparison Macros (Expression-style)
// For performance, only int and float types are supported in arithmetic operations.

#define CheckNum(v) do { \
    if ((v).type_ != VAR_INT && (v).type_ != VAR_FLOAT) { \
        FakeluaThrowError(_S, "attempt to perform arithmetic on non-numeric value"); \
    } \
} while(0)

#define CheckInt(v, result) do { \
    if ((v).type_ == VAR_INT) { (result) = (v).data_.i; } \
    else if ((v).type_ == VAR_FLOAT) { \
        double __d = (v).data_.f; \
        int64_t __i = (int64_t)__d; \
        if ((double)__i != __d) { FakeluaThrowError(_S, "number has no integer representation"); } \
        (result) = __i; \
    } else { \
        FakeluaThrowError(_S, "attempt to perform bitwise operation on non-numeric value"); \
        (result) = 0; \
    } \
} while(0)

#define OpAdd(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_INT(res, _ra.data_.i + _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_FLOAT(res, _f1 + _f2); } \
} while(0)

#define OpSub(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_INT(res, _ra.data_.i - _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_FLOAT(res, _f1 - _f2); } \
} while(0)

#define OpMul(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_INT(res, _ra.data_.i * _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_FLOAT(res, _f1 * _f2); } \
} while(0)

#define OpDiv(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
    double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
    SET_FLOAT(res, _f1 / _f2); \
} while(0)

#define OpFloorDiv(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { \
        if (_rb.data_.i == 0) { FakeluaThrowError(_S, "floor division by zero"); } \
        int64_t _q = _ra.data_.i / _rb.data_.i; \
        if ((_ra.data_.i ^ _rb.data_.i) < 0 && _ra.data_.i % _rb.data_.i != 0) { _q -= 1; } \
        SET_INT(res, _q); \
    } else { \
        double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
        double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
        SET_FLOAT(res, floor(_f1 / _f2)); \
    } \
} while(0)

#define OpPow(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
    double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
    SET_FLOAT(res, pow(_f1, _f2)); \
} while(0)

#define OpMod(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { \
        if (_rb.data_.i == 0) { FakeluaThrowError(_S, "modulo by zero"); } \
        int64_t _q = _ra.data_.i / _rb.data_.i; \
        if ((_ra.data_.i ^ _rb.data_.i) < 0 && _ra.data_.i % _rb.data_.i != 0) { _q -= 1; } \
        SET_INT(res, _ra.data_.i - _rb.data_.i * _q); \
    } else { \
        double _fa = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
        double _fb = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
        SET_FLOAT(res, _fa - _fb * floor(_fa / _fb)); \
    } \
} while(0)

#define OpBitAnd(a, b, res) do { int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); SET_INT(res, _ai & _bi); } while(0)

#define OpBitXor(a, b, res) do { int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); SET_INT(res, _ai ^ _bi); } while(0)

#define OpBitOr(a, b, res) do { int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); SET_INT(res, _ai | _bi); } while(0)

#define OpRightShift(a, b, res) do { \
    int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); \
    if (_bi >= 0) { SET_INT(res, (int64_t)((uint64_t)_ai >> _bi)); } \
    else { SET_INT(res, (int64_t)((uint64_t)_ai << (-(int64_t)_bi))); } \
} while(0)

#define OpLeftShift(a, b, res) do { \
    int64_t _ai; int64_t _bi; CheckInt(a, _ai); CheckInt(b, _bi); \
    if (_bi >= 0) { SET_INT(res, (int64_t)((uint64_t)_ai << _bi)); } \
    else { SET_INT(res, (int64_t)((uint64_t)_ai >> (-(int64_t)_bi))); } \
} while(0)

#define OpLt(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i < _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 < _f2); } \
} while(0)

#define OpGt(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i > _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 > _f2); } \
} while(0)

#define OpLe(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i <= _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 <= _f2); } \
} while(0)

#define OpGe(a, b, res) do { \
    CVar _ra = (a); CVar _rb = (b); CheckNum(_ra); CheckNum(_rb); \
    if (_ra.type_ == VAR_INT && _rb.type_ == VAR_INT) { SET_BOOL(res, _ra.data_.i >= _rb.data_.i); } \
    else { double _f1 = (_ra.type_ == VAR_INT) ? (double)_ra.data_.i : _ra.data_.f; \
           double _f2 = (_rb.type_ == VAR_INT) ? (double)_rb.data_.i : _rb.data_.f; \
           SET_BOOL(res, _f1 >= _f2); } \
} while(0)

#define OpEq(a, b, res) do { bool _eq; VarEqual(a, b, _eq); SET_BOOL(res, _eq); } while(0)

#define OpNe(a, b, res) do { bool _eq; VarEqual(a, b, _eq); SET_BOOL(res, !_eq); } while(0)

#define OpNot(a, res) do { bool _bt; IsTrue(a, _bt); SET_BOOL(res, !_bt); } while(0)

#define OpUnaryMinus(a, res) do { \
    CVar _ra = (a); CheckNum(_ra); \
    if (_ra.type_ == VAR_INT) { SET_INT(res, -_ra.data_.i); } \
    else { SET_FLOAT(res, -_ra.data_.f); } \
} while(0)

#define OpBitNot(a, res) do { int64_t _ai; CheckInt(a, _ai); SET_INT(res, ~_ai); } while(0)

#define OpLen(a, res) do { \
    CVar _lv = (a); \
    if (_lv.type_ == VAR_STRING) { SET_INT(res, STR_SIZE(_lv.data_.s)); } \
    else if (_lv.type_ == VAR_STRINGID) { SET_INT(res, STR_SIZE((VarString *)_lv.data_.i)); } \
    else if (_lv.type_ == VAR_TABLE) { SET_INT(res, TABLE_SIZE(_lv.data_.t)); } \
    else { FakeluaThrowError(_S, "attempt to get length of a non-string/table value"); } \
} while(0)

static inline int FlVarToStr(CVar v, char *buf, int buf_size) {
    switch (v.type_) {
        case VAR_NIL: memcpy(buf, "nil", 3); buf[3] = '\0'; return 3;
        case VAR_BOOL: if (v.data_.b) { memcpy(buf, "true", 4); buf[4] = '\0'; return 4; } else { memcpy(buf, "false", 5); buf[5] = '\0'; return 5; }
        case VAR_INT: return snprintf(buf, buf_size, "%lld", (long long)v.data_.i);
        case VAR_FLOAT: return snprintf(buf, buf_size, "%.14g", v.data_.f);
        case VAR_STRING:
        case VAR_STRINGID: FakeluaThrowError(_S, "FlVarToStr: string type should be handled by caller"); return 0;
        default: memcpy(buf, "table", 5); buf[5] = '\0'; return 5;
    }
}

static inline CVar FlConcat(CVar a, CVar b) {
    char buf_a[256], buf_b[256];
    const char *sa = buf_a; int la;
    const char *sb = buf_b; int lb;
    /* Convert a */
    if (a.type_ == VAR_STRING) { sa = STR_DATA(a.data_.s); la = STR_SIZE(a.data_.s); }
    else if (a.type_ == VAR_STRINGID) { VarString *vs = (VarString *)a.data_.i; sa = STR_DATA(vs); la = STR_SIZE(vs); }
    else { la = FlVarToStr(a, buf_a, sizeof(buf_a)); }
    /* Convert b */
    if (b.type_ == VAR_STRING) { sb = STR_DATA(b.data_.s); lb = STR_SIZE(b.data_.s); }
    else if (b.type_ == VAR_STRINGID) { VarString *vs = (VarString *)b.data_.i; sb = STR_DATA(vs); lb = STR_SIZE(vs); }
    else { lb = FlVarToStr(b, buf_b, sizeof(buf_b)); }
    /* Allocate result */
    int total = la + lb;
    if (total < la || total < lb) { FakeluaThrowError(_S, "string concatenation result too long"); }
    VarString *vs = (VarString *)FakeluaAllocTemp(_S, sizeof(VarString) + total);
    vs->size_ = total;
    vs->hash_ = 0;
    memcpy(vs->data_, sa, la);
    memcpy(vs->data_ + la, sb, lb);
    CVar result;
    result.type_ = VAR_STRING;
    result.flag_ = 0;
    result.data_.s = vs;
    return result;
}

// GET_TABLE_ENTRY(tbl, idx, k, v): fetch key and value at active index idx from a CVar table.
// Works for both small-table mode (bucket_count_ == 0, uses quick_data_[]) and
// hash-table mode (uses active_list_[] + nodes_[]).
#define GET_TABLE_ENTRY(tbl, idx, k, v) do { \
    if ((tbl).data_.t->bucket_count_ == 0) { \
        (k) = (tbl).data_.t->quick_data_[(idx)].key; \
        (v) = (tbl).data_.t->quick_data_[(idx)].val; \
    } else { \
        uint32_t __gti_node_idx = (tbl).data_.t->active_list_[(idx)]; \
        (k) = (tbl).data_.t->nodes_[__gti_node_idx].entry.key; \
        (v) = (tbl).data_.t->nodes_[__gti_node_idx].entry.val; \
    } \
} while(0)

)";
}

void CGen::GenerateGlobal(CompileResult &cr) {
    *cur_output_ << "// ===== Global Variables =====\n\n";

    in_global_init_ = true;

    // 静态全局的CVar
    // 定义初始化器宏
    *cur_output_ << "static const CVar kNil = (CVar){.type_ = VAR_NIL};\n";
    *cur_output_ << "static const CVar kTrue = (CVar){.type_ = VAR_BOOL, .data_.b = true};\n";
    *cur_output_ << "static const CVar kFalse = (CVar){.type_ = VAR_BOOL, .data_.b = false};\n";

    // 遍历顶层的 local 变量定义，生成全局常量
    const auto chunk = cr.chunk;
    DEBUG_ASSERT(chunk->Type() == SyntaxTreeType::Block);

    for (const auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(chunk); const auto &stmt: block->Stmts()) {
        if (stmt->Type() == SyntaxTreeType::LocalVar) {
            const auto local_var = std::dynamic_pointer_cast<SyntaxTreeLocalVar>(stmt);
            const auto namelist = local_var->Namelist();
            const auto explist = local_var->Explist();

            if (!namelist || !explist) {
                continue;
            }

            DEBUG_ASSERT(namelist->Type() == SyntaxTreeType::NameList);
            DEBUG_ASSERT(explist->Type() == SyntaxTreeType::ExpList);

            const auto namelist_ptr = std::dynamic_pointer_cast<SyntaxTreeNamelist>(namelist);
            const auto explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(explist);
            const auto &names = namelist_ptr->Names();
            auto &exps = explist_ptr->Exps();

            // 变量名和表达式数量必须匹配
            if (names.size() != exps.size()) {
                ThrowError(std::format("local variable count {} not match expression count {}", names.size(), exps.size()), stmt);
            }

            for (size_t i = 0; i < names.size(); ++i) {
                const auto &name = names[i];
                const auto &exp = exps[i];

                // 检查是否重复定义
                if (global_const_vars_.contains(name)) {
                    ThrowError("duplicate global const variable: " + name, stmt);
                }

                // 编译表达式为 CVar 初始化字符串
                std::string cvar_init = CompileExp(exp);

                // 生成静态全局变量
                *cur_output_ << "static const CVar " << name << " = " << cvar_init << ";\n";

                // 记录变量名
                global_const_vars_.insert(name);
            }
        }
    }

    in_global_init_ = false;

    *cur_output_ << "\n";
}

void CGen::GenerateDecls(CompileResult &cr) {
    *cur_output_ << "\n// ===== Function Declarations =====\n\n";

    std::unordered_map<std::string, std::vector<std::string>> func_decls;// func name -> list of parameter types (for overloads)

    const auto chunk = cr.chunk;
    DEBUG_ASSERT(chunk->Type() == SyntaxTreeType::Block);
    for (const auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(chunk); auto &stmt: block->Stmts()) {
        std::string name;
        SyntaxTreeInterfacePtr funcbody;
        if (stmt->Type() == SyntaxTreeType::Function) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeFunction>(stmt);
            name = CompileFuncName(func->Funcname());
            funcbody = func->Funcbody();
        } else if (stmt->Type() == SyntaxTreeType::LocalFunction) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeLocalFunction>(stmt);
            name = func->Name();
            funcbody = func->Funcbody();
        }

        if (!funcbody) {
            continue;
        }

        DEBUG_ASSERT(funcbody->Type() == SyntaxTreeType::FuncBody);
        const auto funcbody_ptr = std::dynamic_pointer_cast<SyntaxTreeFuncbody>(funcbody);
        const auto parlist = funcbody_ptr->Parlist();
        std::vector<std::string> func_params;
        if (parlist) {
            func_params = CompileParList(parlist);
        }
        func_decls[name] = func_params;
    }

    for (const auto &[name, params]: func_decls) {
        // 生成函数声明
        *cur_output_ << "CVar " << name << "(";
        for (size_t i = 0; i < params.size(); ++i) {
            if (i > 0) {
                *cur_output_ << ", ";
            }
            *cur_output_ << "CVar " << params[i];
        }
        *cur_output_ << ");\n";

        // 记录函数参数数量
        cr.function_names[name] = static_cast<int>(params.size());
    }

    *cur_output_ << "\n";
}

std::string CGen::CompileFuncName(const SyntaxTreeInterfacePtr &ptr) {
    DEBUG_ASSERT(ptr->Type() == SyntaxTreeType::FuncName);

    std::string ret;

    const auto name = std::dynamic_pointer_cast<SyntaxTreeFuncname>(ptr);
    const auto funcnamelistptr = name->FuncNameList();

    std::vector<std::string> namelist;

    DEBUG_ASSERT(funcnamelistptr->Type() == SyntaxTreeType::FuncNameList);
    const auto funcnamelist = std::dynamic_pointer_cast<SyntaxTreeFuncnamelist>(funcnamelistptr);
    const auto &names = funcnamelist->Funcnames();
    namelist.insert(namelist.end(), names.begin(), names.end());

    if (namelist.size() != 1) {
        ThrowError(std::format("Unsupported function name with {} parts", namelist.size()), ptr);
    }

    if (!name->ColonName().empty()) {
        ThrowError("Unsupported function name with method definition", ptr);
    }

    return namelist[0];
}

[[noreturn]] void CGen::ThrowError(const std::string &msg, const SyntaxTreeInterfacePtr &ptr) {
    ThrowFakeluaException(
            std::format("Code generate failed, {} at {}:{}:{}", msg, file_name_, ptr->Loc().begin.line, ptr->Loc().begin.column));
}

std::string CGen::GenTab() const {
    return std::string(cur_tab_ * 4, ' ');
}

std::vector<std::string> CGen::CompileParList(const SyntaxTreeInterfacePtr &parlist) {
    DEBUG_ASSERT(parlist->Type() == SyntaxTreeType::ParList);
    const auto parlist_ptr = std::dynamic_pointer_cast<SyntaxTreeParlist>(parlist);

    if (parlist_ptr->VarParams()) {
        ThrowError("varargs (...) is not supported", parlist_ptr);
    }

    if (const auto namelist = parlist_ptr->Namelist()) {
        DEBUG_ASSERT(namelist->Type() == SyntaxTreeType::NameList);
        const auto namelist_ptr = std::dynamic_pointer_cast<SyntaxTreeNamelist>(namelist);
        auto &param_names = namelist_ptr->Names();

        std::set<std::string> param_names_set;
        for (const auto &key: global_const_vars_) {
            param_names_set.insert(key);
        }

        for (auto &name: param_names) {
            if (param_names_set.contains(name)) {
                ThrowError("the param name is duplicated: " + name, namelist_ptr);
            }
            param_names_set.insert(name);
        }

        return param_names;
    }

    return {};
}

void CGen::GenerateImpl(CompileResult &cr) {
    std::stringstream impl;

    const auto chunk = cr.chunk;
    DEBUG_ASSERT(chunk->Type() == SyntaxTreeType::Block);
    for (const auto block = std::dynamic_pointer_cast<SyntaxTreeBlock>(chunk); auto &stmt: block->Stmts()) {
        std::string name;
        SyntaxTreeInterfacePtr funcbody;
        if (stmt->Type() == SyntaxTreeType::Function) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeFunction>(stmt);
            name = CompileFuncName(func->Funcname());
            funcbody = func->Funcbody();
        } else if (stmt->Type() == SyntaxTreeType::LocalFunction) {
            const auto func = std::dynamic_pointer_cast<SyntaxTreeLocalFunction>(stmt);
            name = func->Name();
            funcbody = func->Funcbody();
        }

        if (!funcbody) {
            continue;
        }

        DEBUG_ASSERT(funcbody->Type() == SyntaxTreeType::FuncBody);
        const auto funcbody_ptr = std::dynamic_pointer_cast<SyntaxTreeFuncbody>(funcbody);
        const auto parlist = funcbody_ptr->Parlist();
        std::vector<std::string> func_params;
        if (parlist) {
            func_params = CompileParList(parlist);
        }

        // 生成函数定义头部
        *cur_output_ << "CVar " << name << "(";
        for (size_t i = 0; i < func_params.size(); ++i) {
            if (i > 0) {
                *cur_output_ << ", ";
            }
            *cur_output_ << "CVar " << func_params[i];
        }
        *cur_output_ << ") {\n";

        // 编译函数体：将语句输出缓冲到 body_ss_，临时变量声明缓冲到 func_temp_decls_，
        // 最终将声明提升到函数体顶部，确保 C89 兼容性。
        const auto func_block = funcbody_ptr->Block();
        func_temp_decls_.str("");
        func_temp_decls_.clear();
        body_ss_.str("");
        body_ss_.clear();
        cur_output_ = &body_ss_;
        cur_tab_++;
        CompileStmtBlock(func_block);
        cur_tab_--;
        cur_output_ = &impls_;
        *cur_output_ << func_temp_decls_.str();
        *cur_output_ << body_ss_.str();

        *cur_output_ << "}\n";
    }
}

void CGen::CompileStmtBlock(const SyntaxTreeInterfacePtr &block) {
    DEBUG_ASSERT(block->Type() == SyntaxTreeType::Block);
    const auto block_ptr = std::dynamic_pointer_cast<SyntaxTreeBlock>(block);

    for (const auto &stmts = block_ptr->Stmts(); auto &stmt: stmts) {
        CompileStmt(stmt);
    }
}

void CGen::CompileStmt(const SyntaxTreeInterfacePtr &stmt) {
    switch (stmt->Type()) {
        case SyntaxTreeType::Return: {
            CompileStmtReturn(stmt);
            break;
        }
        case SyntaxTreeType::LocalVar: {
            CompileStmtLocalVar(stmt);
            break;
        }
        case SyntaxTreeType::Assign: {
            CompileStmtAssign(stmt);
            break;
        }
        case SyntaxTreeType::FunctionCall: {
            CompileStmtFunctioncall(stmt);
            break;
        }
        case SyntaxTreeType::Label: {
            ThrowError("label is not supported", stmt);
            break;
        }
        case SyntaxTreeType::Goto: {
            ThrowError("goto is not supported", stmt);
            break;
        }
        case SyntaxTreeType::Block: {
            CompileStmtBlock(stmt);
            break;
        }
        case SyntaxTreeType::While: {
            CompileStmtWhile(stmt);
            break;
        }
        case SyntaxTreeType::Repeat: {
            CompileStmtRepeat(stmt);
            break;
        }
        case SyntaxTreeType::If: {
            CompileStmtIf(stmt);
            break;
        }
        case SyntaxTreeType::Break: {
            CompileStmtBreak(stmt);
            break;
        }
        case SyntaxTreeType::ForLoop: {
            CompileStmtForLoop(stmt);
            break;
        }
        case SyntaxTreeType::ForIn: {
            CompileStmtForIn(stmt);
            break;
        }
        default: {
            ThrowError(std::format("not support stmt type: {}", SyntaxTreeTypeToString(stmt->Type())), stmt);
        }
    }
}

void CGen::CompileStmtReturn(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::Return);
    const auto return_stmt = std::dynamic_pointer_cast<SyntaxTreeReturn>(stmt);

    auto explist = return_stmt->Explist();
    if (!explist) {
        // 默认返回 nil
        explist = std::make_shared<SyntaxTreeExplist>(return_stmt->Loc());
        const auto exp = std::make_shared<SyntaxTreeExp>(return_stmt->Loc());
        exp->SetType("nil");
        std::dynamic_pointer_cast<SyntaxTreeExplist>(explist)->AddExp(exp);
    }

    const auto explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(explist);
    DEBUG_ASSERT(!explist_ptr->Exps().empty());
    if (explist_ptr->Exps().empty()) {
        // 默认返回 nil
        const auto exp = std::make_shared<SyntaxTreeExp>(return_stmt->Loc());
        exp->SetType("nil");
        explist_ptr->AddExp(exp);
    } else if (explist_ptr->Exps().size() > 1) {
        // 不支持多返回值
        ThrowError("multiple return values is not supported", explist_ptr);
    }

    const auto exp = explist_ptr->Exps()[0];
    const auto ret = CompileExp(exp);

    *cur_output_ << GenTab() << "return " << ret << ";\n";
}

void CGen::CompileStmtLocalVar(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::LocalVar);
    const auto local_var = std::dynamic_pointer_cast<SyntaxTreeLocalVar>(stmt);
    const auto namelist = local_var->Namelist();

    if (!namelist) {
        return;
    }

    DEBUG_ASSERT(namelist->Type() == SyntaxTreeType::NameList);
    const auto namelist_ptr = std::dynamic_pointer_cast<SyntaxTreeNamelist>(namelist);
    const auto &names = namelist_ptr->Names();

    std::vector<SyntaxTreeInterfacePtr> exps;
    if (const auto explist = local_var->Explist()) {
        DEBUG_ASSERT(explist->Type() == SyntaxTreeType::ExpList);
        const auto explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(explist);
        exps = explist_ptr->Exps();
    }

    for (size_t i = 0; i < names.size(); ++i) {
        const auto &name = names[i];

        if (global_const_vars_.contains(name)) {
            ThrowError("local variable conflicts with global constant: " + name, stmt);
        }

        const std::string init = (i < exps.size()) ? CompileExp(exps[i]) : "kNil";
        *cur_output_ << GenTab() << "CVar " << name << " = " << init << ";\n";
    }
}

void CGen::CompileStmtAssign(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::Assign);
    const auto assign = std::dynamic_pointer_cast<SyntaxTreeAssign>(stmt);

    const auto varlist = assign->Varlist();
    DEBUG_ASSERT(varlist->Type() == SyntaxTreeType::VarList);
    const auto varlist_ptr = std::dynamic_pointer_cast<SyntaxTreeVarlist>(varlist);
    const auto &vars = varlist_ptr->Vars();

    std::vector<SyntaxTreeInterfacePtr> exps;
    if (const auto explist = assign->Explist()) {
        DEBUG_ASSERT(explist->Type() == SyntaxTreeType::ExpList);
        const auto explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(explist);
        exps = explist_ptr->Exps();
    }

    // PreprocessSplitAssign guarantees exactly 1 var and 1 exp at this point
    DEBUG_ASSERT(vars.size() == 1);
    if (exps.size() != 1) {
        ThrowError(std::format("CompileStmtAssign: expected 1 expression, got {}", exps.size()), assign);
    }

    const std::string rhs = CompileExp(exps[0]);

    DEBUG_ASSERT(vars[0]->Type() == SyntaxTreeType::Var);
    const auto v_ptr = std::dynamic_pointer_cast<SyntaxTreeVar>(vars[0]);
    const auto &vtype = v_ptr->GetType();

    // PreprocessTableAssign rewrites square/dot assignments to FAKELUA_SET_TABLE calls,
    // so only simple variable assignments can reach here.
    DEBUG_ASSERT(vtype == "simple");
    const auto &name = v_ptr->GetName();
    *cur_output_ << GenTab() << name << " = " << rhs << ";\n";
}

void CGen::CompileStmtFunctioncall(const SyntaxTreeInterfacePtr &shared) {
    CompileFunctioncall(shared);
}

void CGen::CompileStmtWhile(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::While);
    const auto while_stmt = std::dynamic_pointer_cast<SyntaxTreeWhile>(stmt);

    const auto tmp_bool = std::format("flua_wbt_{}", tmp_var_counter_++);
    func_temp_decls_ << "    bool " << tmp_bool << ";\n";

    *cur_output_ << GenTab() << "while (1) {\n";
    cur_tab_++;

    const auto cond = CompileExp(while_stmt->Exp());
    *cur_output_ << GenTab() << std::format("IsTrue(({}), {});\n", cond, tmp_bool);
    *cur_output_ << GenTab() << std::format("if (!{}) break;\n", tmp_bool);

    CompileStmtBlock(while_stmt->Block());

    cur_tab_--;
    *cur_output_ << GenTab() << "}\n";
}

void CGen::CompileStmtRepeat(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::Repeat);
    const auto repeat_stmt = std::dynamic_pointer_cast<SyntaxTreeRepeat>(stmt);

    const auto tmp_bool = std::format("flua_rbt_{}", tmp_var_counter_++);
    func_temp_decls_ << "    bool " << tmp_bool << ";\n";

    *cur_output_ << GenTab() << "do {\n";
    cur_tab_++;

    CompileStmtBlock(repeat_stmt->Block());

    const auto cond = CompileExp(repeat_stmt->Exp());
    *cur_output_ << GenTab() << std::format("IsTrue(({}), {});\n", cond, tmp_bool);
    *cur_output_ << GenTab() << std::format("if ({}) break;\n", tmp_bool);

    cur_tab_--;
    *cur_output_ << GenTab() << "} while (1);\n";
}

void CGen::CompileStmtIf(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::If);
    const auto if_stmt = std::dynamic_pointer_cast<SyntaxTreeIf>(stmt);

    const auto tmp_bool = std::format("flua_ibt_{}", tmp_var_counter_++);
    func_temp_decls_ << "    bool " << tmp_bool << ";\n";

    const auto cond = CompileExp(if_stmt->Exp());
    *cur_output_ << GenTab() << std::format("IsTrue(({}), {});\n", cond, tmp_bool);
    *cur_output_ << GenTab() << std::format("if ({}) {{\n", tmp_bool);
    cur_tab_++;
    CompileStmtBlock(if_stmt->Block());
    cur_tab_--;
    *cur_output_ << GenTab() << "}";

    int elseif_depth = 0;
    if (const auto elseifs_node = if_stmt->ElseIfs()) {
        const auto elseif_list = std::dynamic_pointer_cast<SyntaxTreeElseiflist>(elseifs_node);
        for (size_t i = 0; i < elseif_list->ElseifSize(); ++i) {
            *cur_output_ << " else {\n";
            cur_tab_++;
            elseif_depth++;

            const auto etmp_bool = std::format("flua_ibt_{}", tmp_var_counter_++);
            func_temp_decls_ << "    bool " << etmp_bool << ";\n";

            const auto econd = CompileExp(elseif_list->ElseifExp(i));
            *cur_output_ << GenTab() << std::format("IsTrue(({}), {});\n", econd, etmp_bool);
            *cur_output_ << GenTab() << std::format("if ({}) {{\n", etmp_bool);
            cur_tab_++;
            CompileStmtBlock(elseif_list->ElseifBlock(i));
            cur_tab_--;
            *cur_output_ << GenTab() << "}";
        }
    }

    if (const auto else_block = if_stmt->ElseBlock()) {
        *cur_output_ << " else {\n";
        cur_tab_++;
        CompileStmtBlock(else_block);
        cur_tab_--;
        *cur_output_ << GenTab() << "}";
    }

    for (int i = 0; i < elseif_depth; ++i) {
        *cur_output_ << "\n";
        cur_tab_--;
        *cur_output_ << GenTab() << "}";
    }

    *cur_output_ << "\n";
}

void CGen::CompileStmtBreak(const SyntaxTreeInterfacePtr &stmt) {
    *cur_output_ << GenTab() << "break;\n";
}

void CGen::CompileStmtForLoop(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::ForLoop);
    const auto for_stmt = std::dynamic_pointer_cast<SyntaxTreeForLoop>(stmt);

    // Allocate generated C variable names for loop control (hoisted to function top)
    const auto ctrl_var = std::format("flua_for_ctrl_{}", tmp_var_counter_++);    // current value
    const auto end_var = std::format("flua_for_end_{}", tmp_var_counter_++);      // end value
    const auto step_var = std::format("flua_for_step_{}", tmp_var_counter_++);    // step value
    const auto step_pos_var = std::format("flua_for_step_pos_{}", tmp_var_counter_++); // step > 0 flag
    const auto cond_var = std::format("flua_for_cond_{}", tmp_var_counter_++);    // loop condition
    const auto cmp_var = std::format("flua_for_cmp_{}", tmp_var_counter_++);      // comparison temp

    func_temp_decls_ << "    CVar " << ctrl_var << ";\n";
    func_temp_decls_ << "    CVar " << end_var << ";\n";
    func_temp_decls_ << "    CVar " << step_var << ";\n";
    func_temp_decls_ << "    bool " << step_pos_var << ";\n";
    func_temp_decls_ << "    bool " << cond_var << ";\n";
    func_temp_decls_ << "    CVar " << cmp_var << ";\n";

    // Evaluate begin, end, step expressions
    const auto begin_expr = CompileExp(for_stmt->ExpBegin());
    *cur_output_ << GenTab() << ctrl_var << " = " << begin_expr << ";\n";

    const auto end_expr = CompileExp(for_stmt->ExpEnd());
    *cur_output_ << GenTab() << end_var << " = " << end_expr << ";\n";

    if (for_stmt->ExpStep()) {
        const auto step_expr = CompileExp(for_stmt->ExpStep());
        *cur_output_ << GenTab() << step_var << " = " << step_expr << ";\n";
    } else {
        *cur_output_ << GenTab() << "SET_INT(" << step_var << ", 1);\n";
    }

    // Determine step direction once before the loop
    *cur_output_ << GenTab() << "if (" << step_var << ".type_ == VAR_INT) { " << step_pos_var << " = (" << step_var << ".data_.i > 0); }\n";
    *cur_output_ << GenTab() << "else if (" << step_var << ".type_ == VAR_FLOAT) { " << step_pos_var << " = (" << step_var << ".data_.f > 0.0); }\n";
    *cur_output_ << GenTab() << "else { FakeluaThrowError(_S, \"'for' step must be a number\"); " << step_pos_var << " = 1; }\n";

    *cur_output_ << GenTab() << "while (1) {\n";
    cur_tab_++;

    // Check loop condition: if step > 0: ctrl <= end; else: ctrl >= end
    *cur_output_ << GenTab() << "if (" << step_pos_var << ") {\n";
    cur_tab_++;
    *cur_output_ << GenTab() << std::format("OpLe(({0}), ({1}), {2});\n", ctrl_var, end_var, cmp_var);
    cur_tab_--;
    *cur_output_ << GenTab() << "} else {\n";
    cur_tab_++;
    *cur_output_ << GenTab() << std::format("OpGe(({0}), ({1}), {2});\n", ctrl_var, end_var, cmp_var);
    cur_tab_--;
    *cur_output_ << GenTab() << "}\n";

    *cur_output_ << GenTab() << std::format("IsTrue(({0}), {1});\n", cmp_var, cond_var);
    *cur_output_ << GenTab() << std::format("if (!{}) break;\n", cond_var);

    // Declare the loop variable visible in the body
    const auto &loop_var_name = for_stmt->Name();
    *cur_output_ << GenTab() << "CVar " << loop_var_name << " = " << ctrl_var << ";\n";

    // Compile the loop body
    CompileStmtBlock(for_stmt->Block());

    // Increment the control variable
    *cur_output_ << GenTab() << std::format("OpAdd(({0}), ({1}), {2});\n", ctrl_var, step_var, ctrl_var);

    cur_tab_--;
    *cur_output_ << GenTab() << "}\n";
}

void CGen::CompileStmtForIn(const SyntaxTreeInterfacePtr &stmt) {
    DEBUG_ASSERT(stmt->Type() == SyntaxTreeType::ForIn);
    const auto for_in = std::dynamic_pointer_cast<SyntaxTreeForIn>(stmt);

    // Get iteration variable names (k, v or just k)
    const auto namelist = for_in->Namelist();
    DEBUG_ASSERT(namelist->Type() == SyntaxTreeType::NameList);
    const auto namelist_ptr = std::dynamic_pointer_cast<SyntaxTreeNamelist>(namelist);
    const auto &names = namelist_ptr->Names();
    if (names.empty() || names.size() > 2) {
        ThrowError(std::format("for in namelist size must be 1 or 2, but got {}", names.size()), namelist);
    }

    // Explist must contain exactly one expression: pairs(t) or ipairs(t)
    const auto explist = for_in->Explist();
    DEBUG_ASSERT(explist->Type() == SyntaxTreeType::ExpList);
    const auto explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(explist);
    if (explist_ptr->Exps().size() != 1) {
        ThrowError(std::format("for in explist size must be 1, but got {}", explist_ptr->Exps().size()), explist);
    }

    // The expression must be a call to pairs() or ipairs()
    const auto exp = explist_ptr->Exps()[0];
    DEBUG_ASSERT(exp->Type() == SyntaxTreeType::Exp);
    const auto exp_ptr = std::dynamic_pointer_cast<SyntaxTreeExp>(exp);
    if (exp_ptr->ExpType() != "prefixexp") {
        ThrowError("for in expression must be a pairs() or ipairs() call", exp);
    }
    const auto prefixexp = exp_ptr->Right();
    DEBUG_ASSERT(prefixexp->Type() == SyntaxTreeType::PrefixExp);
    const auto pe_ptr = std::dynamic_pointer_cast<SyntaxTreePrefixexp>(prefixexp);
    if (pe_ptr->GetType() != "functioncall") {
        ThrowError("for in expression must be a function call", exp);
    }
    const auto functioncall = pe_ptr->GetValue();
    DEBUG_ASSERT(functioncall->Type() == SyntaxTreeType::FunctionCall);
    const auto fc_ptr = std::dynamic_pointer_cast<SyntaxTreeFunctioncall>(functioncall);

    // Check that the function is pairs or ipairs
    const auto func_pe = fc_ptr->prefixexp();
    DEBUG_ASSERT(func_pe->Type() == SyntaxTreeType::PrefixExp);
    const auto func_pe_ptr = std::dynamic_pointer_cast<SyntaxTreePrefixexp>(func_pe);
    if (func_pe_ptr->GetType() != "var") {
        ThrowError("for in: only pairs() or ipairs() are supported", functioncall);
    }
    const auto func_var = std::dynamic_pointer_cast<SyntaxTreeVar>(func_pe_ptr->GetValue());
    const auto &func_name = func_var->GetName();
    if (func_name != "pairs" && func_name != "ipairs") {
        ThrowError(std::format("for in: only pairs() or ipairs() are supported, got '{}'", func_name), functioncall);
    }

    // Extract the table argument from pairs(t) / ipairs(t)
    const auto args_node = fc_ptr->Args();
    DEBUG_ASSERT(args_node->Type() == SyntaxTreeType::Args);
    const auto args_ptr = std::dynamic_pointer_cast<SyntaxTreeArgs>(args_node);
    if (args_ptr->GetType() != "explist") {
        ThrowError("for in: pairs/ipairs argument must be an expression list", args_node);
    }
    const auto args_explist = args_ptr->Explist();
    const auto args_explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(args_explist);
    if (args_explist_ptr->Exps().size() != 1) {
        ThrowError(std::format("for in: pairs/ipairs must have exactly one argument, got {}", args_explist_ptr->Exps().size()), args_node);
    }

    // Compile the table expression
    const auto tbl_expr = CompileExp(args_explist_ptr->Exps()[0]);

    // Allocate generated C variable names for iteration state (hoisted to function top)
    const auto tbl_var = std::format("flua_fi_tbl_{}", tmp_var_counter_++);  // table
    const auto sz_var = std::format("flua_fi_sz_{}", tmp_var_counter_++);    // element count
    const auto idx_var = std::format("flua_fi_idx_{}", tmp_var_counter_++);  // current index

    func_temp_decls_ << "    CVar " << tbl_var << ";\n";
    func_temp_decls_ << "    uint32_t " << sz_var << ";\n";
    func_temp_decls_ << "    uint32_t " << idx_var << ";\n";

    // Evaluate and validate the table
    *cur_output_ << GenTab() << tbl_var << " = " << tbl_expr << ";\n";
    *cur_output_ << GenTab() << "if (" << tbl_var << ".type_ != VAR_TABLE) { FakeluaThrowError(_S, \"for in: not a table\"); }\n";
    *cur_output_ << GenTab() << sz_var << " = " << tbl_var << ".data_.t->count_;\n";

    *cur_output_ << GenTab() << "for (" << idx_var << " = 0; " << idx_var << " < " << sz_var << "; " << idx_var << "++) {\n";
    cur_tab_++;

    // Get key (and optionally value) for this iteration via GET_TABLE_ENTRY macro
    const auto &key_name = names[0];
    if (names.size() >= 2) {
        const auto &val_name = names[1];
        *cur_output_ << GenTab() << "CVar " << key_name << "; CVar " << val_name << ";\n";
        *cur_output_ << GenTab() << std::format("GET_TABLE_ENTRY({}, {}, {}, {});\n", tbl_var, idx_var, key_name, val_name);
    } else {
        const auto dummy_val = std::format("flua_fi_dummy_val_{}", tmp_var_counter_++);
        func_temp_decls_ << "    CVar " << dummy_val << ";\n";
        *cur_output_ << GenTab() << "CVar " << key_name << ";\n";
        *cur_output_ << GenTab() << std::format("GET_TABLE_ENTRY({}, {}, {}, {});\n", tbl_var, idx_var, key_name, dummy_val);
    }

    // Compile the loop body
    CompileStmtBlock(for_in->Block());

    cur_tab_--;
    *cur_output_ << GenTab() << "}\n";
}

std::string CGen::CompileExp(const SyntaxTreeInterfacePtr &exp) {
    DEBUG_ASSERT(exp->Type() == SyntaxTreeType::Exp);
    // start to compile the expression
    const auto e = std::dynamic_pointer_cast<SyntaxTreeExp>(exp);
    const auto &ExpType = e->ExpType();
    const auto &value = e->ExpValue();

    DEBUG_ASSERT(ExpType == "nil" || ExpType == "false" || ExpType == "true" || ExpType == "number" || ExpType == "string" ||
                 ExpType == "prefixexp" || ExpType == "VarParams" || ExpType == "tableconstructor" || ExpType == "binop" ||
                 ExpType == "unop")

    if (ExpType == "nil") {
        if (in_global_init_) {
            return "(CVar){.type_ = VAR_NIL}";
        } else {
            return "kNil";
        }
    } else if (ExpType == "false") {
        if (in_global_init_) {
            return "(CVar){.type_ = VAR_BOOL, .data_.b = false}";
        } else {
            return "kFalse";
        }
    } else if (ExpType == "true") {
        if (in_global_init_) {
            return "(CVar){.type_ = VAR_BOOL, .data_.b = true}";
        } else {
            return "kTrue";
        }
    } else if (ExpType == "number") {
        if (IsInteger(value)) {
            // eg: (CVar){.type_ = VAR_INT, .data_.i = 42}
            auto i = ToInteger(value);
            return std::format("(CVar){{.type_ = VAR_INT, .data_.i = {}}}", i);
        } else {
            auto f = ToFloat(value);
            return std::format("(CVar){{.type_ = VAR_FLOAT, .data_.f = {}}}", f);
        }
    } else if (ExpType == "string") {
        auto id = s_->GetConstString().Alloc(value);
        return std::format("(CVar){{.type_ = VAR_STRINGID, .data_.i = {}}}", id);
    } else if (ExpType == "prefixexp") {
        const auto pe = e->Right();
        return CompilePrefixexp(pe);
    } else if (ExpType == "VarParams") {
        ThrowError("... is not supported", e);
    } else if (ExpType == "tableconstructor") {
        const auto tc = e->Right();
        return CompileTableconstructor(tc);
    } else if (ExpType == "binop") {
        const auto left = e->Left();
        const auto right = e->Right();
        const auto op = e->Op();
        return CompileBinop(left, right, op);
    } else if (ExpType == "unop") {
        const auto right = e->Right();
        const auto op = e->Op();
        return CompileUnop(right, op);
    }

    DEBUG_ASSERT(false && "unreachable");
    ThrowError("unsupported expression type: " + ExpType, e);
}

std::string CGen::CompilePrefixexp(const SyntaxTreeInterfacePtr &pe) {
    DEBUG_ASSERT(pe->Type() == SyntaxTreeType::PrefixExp);
    const auto pe_ptr = std::dynamic_pointer_cast<SyntaxTreePrefixexp>(pe);

    const auto &pe_type = pe_ptr->GetType();
    const auto value = pe_ptr->GetValue();

    DEBUG_ASSERT(pe_type == "var" || pe_type == "functioncall" || pe_type == "exp");

    if (pe_type == "var") {
        return CompileVar(value);
    } else if (pe_type == "functioncall") {
        return CompileFunctioncall(value);
    } else /*if (pe_type == "exp")*/ {
        return CompileExp(value);
    }
}

std::string CGen::CompileTableconstructor(const SyntaxTreeInterfacePtr &tc) {
    if (in_global_init_) {
        ThrowError("table constructor is not supported in global variable initialization", tc);
    }

    DEBUG_ASSERT(tc->Type() == SyntaxTreeType::TableConstructor);
    const auto tc_ptr = std::dynamic_pointer_cast<SyntaxTreeTableconstructor>(tc);

    const auto var_name = std::format("flua_tbl_{}", tmp_var_counter_++);

    func_temp_decls_ << "    " << "CVar " << var_name << ";\n";
    *cur_output_ << GenTab() << "SET_TABLE(" << var_name << ");\n";

    const auto fieldlist = tc_ptr->Fieldlist();
    if (fieldlist) {
        DEBUG_ASSERT(fieldlist->Type() == SyntaxTreeType::FieldList);
        const auto fieldlist_ptr = std::dynamic_pointer_cast<SyntaxTreeFieldlist>(fieldlist);

        int array_idx = 1;
        for (const auto &field: fieldlist_ptr->Fields()) {
            DEBUG_ASSERT(field->Type() == SyntaxTreeType::Field);
            const auto field_ptr = std::dynamic_pointer_cast<SyntaxTreeField>(field);
            const auto &ftype = field_ptr->GetType();

            const auto value_exp = field_ptr->Value();
            const auto value_str = CompileExp(value_exp);

            std::string key_str;
            if (ftype == "object") {
                // name = value: key is a string identifier
                const auto name = field_ptr->Name();
                const auto id = s_->GetConstString().Alloc(name);
                key_str = std::format("(CVar){{.type_ = VAR_STRINGID, .data_.i = {}}}", id);
            } else {
                // array: either [exp] = value (explicit key) or just exp (sequential index)
                DEBUG_ASSERT(ftype == "array");
                const auto key = field_ptr->Key();
                if (key) {
                    key_str = CompileExp(key);
                } else {
                    key_str = std::format("(CVar){{.type_ = VAR_INT, .data_.i = {}}}", array_idx);
                    ++array_idx;
                }
            }

            *cur_output_ << GenTab() << std::format("FlSetTable({}, {}, {});\n", var_name, key_str, value_str);
        }
    }

    return var_name;
}

std::string CGen::CompileBinop(const SyntaxTreeInterfacePtr &left, const SyntaxTreeInterfacePtr &right, const SyntaxTreeInterfacePtr &op) {
    if (in_global_init_) {
        ThrowError("binary operator is not supported in global variable initialization", op);
    }

    const auto op_ptr = std::dynamic_pointer_cast<SyntaxTreeBinop>(op);
    const auto &op_name = op_ptr->GetOp();

    // Short-circuit operators (AND/OR) need special handling:
    // Right side must only be evaluated when needed.
    if (op_name == "AND" || op_name == "OR") {
        const auto left_str = CompileExp(left);

        const auto tmp = std::format("flua_op_{}", tmp_var_counter_++);
        func_temp_decls_ << "    " << "CVar " << tmp << ";\n";
        const auto tmp_bool = std::format("flua_bt_{}", tmp_var_counter_++);
        func_temp_decls_ << "    " << "bool " << tmp_bool << ";\n";

        *cur_output_ << GenTab() << std::format("IsTrue(({}), {});\n", left_str, tmp_bool);

        if (op_name == "AND") {
            // AND: if left is falsy, return left; else evaluate and return right
            *cur_output_ << GenTab() << std::format("if (!{}) {{\n", tmp_bool);
            cur_tab_++;
            *cur_output_ << GenTab() << std::format("{} = {};\n", tmp, left_str);
            cur_tab_--;
            *cur_output_ << GenTab() << "} else {\n";
            cur_tab_++;
            const auto right_str = CompileExp(right);
            *cur_output_ << GenTab() << std::format("{} = {};\n", tmp, right_str);
            cur_tab_--;
            *cur_output_ << GenTab() << "}\n";
        } else {
            // OR: if left is truthy, return left; else evaluate and return right
            *cur_output_ << GenTab() << std::format("if ({}) {{\n", tmp_bool);
            cur_tab_++;
            *cur_output_ << GenTab() << std::format("{} = {};\n", tmp, left_str);
            cur_tab_--;
            *cur_output_ << GenTab() << "} else {\n";
            cur_tab_++;
            const auto right_str = CompileExp(right);
            *cur_output_ << GenTab() << std::format("{} = {};\n", tmp, right_str);
            cur_tab_--;
            *cur_output_ << GenTab() << "}\n";
        }

        return tmp;
    }

    const auto left_str = CompileExp(left);
    const auto right_str = CompileExp(right);

    const auto tmp = std::format("flua_op_{}", tmp_var_counter_++);
    func_temp_decls_ << "    " << "CVar " << tmp << ";\n";

    // Wrap arguments in parentheses to prevent commas in C compound literals
    // (e.g. (CVar){.type_ = VAR_INT, .data_.i = 2}) from being misinterpreted
    // as macro argument separators by the C preprocessor.
    const auto l = std::format("({})", left_str);
    const auto r = std::format("({})", right_str);

    if (op_name == "PLUS") {
        *cur_output_ << GenTab() << std::format("OpAdd({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "MINUS") {
        *cur_output_ << GenTab() << std::format("OpSub({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "STAR") {
        *cur_output_ << GenTab() << std::format("OpMul({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "SLASH") {
        *cur_output_ << GenTab() << std::format("OpDiv({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "DOUBLE_SLASH") {
        *cur_output_ << GenTab() << std::format("OpFloorDiv({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "POW") {
        *cur_output_ << GenTab() << std::format("OpPow({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "MOD") {
        *cur_output_ << GenTab() << std::format("OpMod({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "BITAND") {
        *cur_output_ << GenTab() << std::format("OpBitAnd({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "XOR") {
        *cur_output_ << GenTab() << std::format("OpBitXor({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "BITOR") {
        *cur_output_ << GenTab() << std::format("OpBitOr({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "RIGHT_SHIFT") {
        *cur_output_ << GenTab() << std::format("OpRightShift({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "LEFT_SHIFT") {
        *cur_output_ << GenTab() << std::format("OpLeftShift({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "CONCAT") {
        *cur_output_ << GenTab() << std::format("{} = FlConcat({}, {});\n", tmp, l, r);
    } else if (op_name == "LESS") {
        *cur_output_ << GenTab() << std::format("OpLt({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "LESS_EQUAL") {
        *cur_output_ << GenTab() << std::format("OpLe({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "MORE") {
        *cur_output_ << GenTab() << std::format("OpGt({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "MORE_EQUAL") {
        *cur_output_ << GenTab() << std::format("OpGe({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "EQUAL") {
        *cur_output_ << GenTab() << std::format("OpEq({}, {}, {});\n", l, r, tmp);
    } else if (op_name == "NOT_EQUAL") {
        *cur_output_ << GenTab() << std::format("OpNe({}, {}, {});\n", l, r, tmp);
    } else {
        ThrowError("binary operator not supported: " + op_name, op);
    }

    return tmp;
}

std::string CGen::CompileUnop(const SyntaxTreeInterfacePtr &right, const SyntaxTreeInterfacePtr &op) {
    if (in_global_init_) {
        ThrowError("unary operator is not supported in global variable initialization", op);
    }

    const auto op_ptr = std::dynamic_pointer_cast<SyntaxTreeUnop>(op);
    const auto &op_name = op_ptr->GetOp();

    const auto right_str = CompileExp(right);

    const auto tmp = std::format("flua_op_{}", tmp_var_counter_++);
    func_temp_decls_ << "    " << "CVar " << tmp << ";\n";

    // Wrap argument in parentheses to protect commas in compound literals from macro parsing
    const auto r = std::format("({})", right_str);

    if (op_name == "NOT") {
        *cur_output_ << GenTab() << std::format("OpNot({}, {});\n", r, tmp);
    } else if (op_name == "MINUS") {
        *cur_output_ << GenTab() << std::format("OpUnaryMinus({}, {});\n", r, tmp);
    } else if (op_name == "BITNOT") {
        *cur_output_ << GenTab() << std::format("OpBitNot({}, {});\n", r, tmp);
    } else if (op_name == "NUMBER_SIGN") {
        *cur_output_ << GenTab() << std::format("OpLen({}, {});\n", r, tmp);
    } else {
        ThrowError("unary operator not supported: " + op_name, op);
    }

    return tmp;
}

std::string CGen::CompileVar(const SyntaxTreeInterfacePtr &v) {
    DEBUG_ASSERT(v->Type() == SyntaxTreeType::Var);
    auto v_ptr = std::dynamic_pointer_cast<SyntaxTreeVar>(v);

    DEBUG_ASSERT(v_ptr->GetType() == "simple" || v_ptr->GetType() == "square" || v_ptr->GetType() == "dot");

    if (const auto &type = v_ptr->GetType(); type == "simple") {
        const auto &name = v_ptr->GetName();
        if (in_global_init_) {
            ThrowError("variable reference is not allowed in global variable initialization", v);
        }
        return name;
    } else if (type == "square") {
        if (in_global_init_) {
            ThrowError("table access is not allowed in global variable initialization", v);
        }
        const auto pe = v_ptr->GetPrefixexp();
        const auto exp = v_ptr->GetExp();
        auto pe_ret = CompilePrefixexp(pe);
        auto exp_ret = CompileExp(exp);

        // 调用table的get函数
        return std::format("FlGetTable({}, {})", pe_ret, exp_ret);
    } else /*if (type == "dot")*/ {
        if (in_global_init_) {
            ThrowError("table access is not allowed in global variable initialization", v);
        }
        const auto pe = v_ptr->GetPrefixexp();
        const auto name = v_ptr->GetName();
        auto pe_ret = CompilePrefixexp(pe);

        const auto name_exp = std::make_shared<SyntaxTreeExp>(v_ptr->Loc());
        name_exp->SetType("string");
        name_exp->SetValue(name);
        auto exp_ret = CompileExp(name_exp);

        // 调用table的get函数
        return std::format("FlGetTable({}, {})", pe_ret, exp_ret);
    }
}

std::string CGen::CompileFunctioncall(const SyntaxTreeInterfacePtr &functioncall) {
    if (in_global_init_) {
        ThrowError("function call is not allowed in global variable initialization", functioncall);
    }

    DEBUG_ASSERT(functioncall->Type() == SyntaxTreeType::FunctionCall);
    const auto fc = std::dynamic_pointer_cast<SyntaxTreeFunctioncall>(functioncall);

    if (!fc->Name().empty()) {
        ThrowError("method calls (:) are not supported", functioncall);
    }

    // Compile arguments
    const auto args_node = fc->Args();
    DEBUG_ASSERT(args_node->Type() == SyntaxTreeType::Args);
    const auto args_ptr = std::dynamic_pointer_cast<SyntaxTreeArgs>(args_node);

    std::vector<std::string> compiled_args;
    const auto &args_type = args_ptr->GetType();
    if (args_type == "explist") {
        const auto explist = args_ptr->Explist();
        DEBUG_ASSERT(explist->Type() == SyntaxTreeType::ExpList);
        const auto explist_ptr = std::dynamic_pointer_cast<SyntaxTreeExplist>(explist);
        for (const auto &exp: explist_ptr->Exps()) {
            compiled_args.push_back(CompileExp(exp));
        }
    } else if (args_type == "tableconstructor") {
        compiled_args.push_back(CompileTableconstructor(args_ptr->Tableconstructor()));
    } else if (args_type == "string") {
        compiled_args.push_back(CompileExp(args_ptr->String()));
    }
    // "empty": no args

    // Determine the function call expression
    const auto pe = fc->prefixexp();
    DEBUG_ASSERT(pe->Type() == SyntaxTreeType::PrefixExp);
    const auto pe_ptr = std::dynamic_pointer_cast<SyntaxTreePrefixexp>(pe);

    std::string call_expr;
    if (pe_ptr->GetType() == "var") {
        const auto var = std::dynamic_pointer_cast<SyntaxTreeVar>(pe_ptr->GetValue());
        if (var->GetType() == "simple") {
            const auto &func_name = var->GetName();
            if (func_name == "FAKELUA_SET_TABLE") {
                // Built-in table assignment: FAKELUA_SET_TABLE(t, k, v) -> FlSetTable(t, k, v)
                if (compiled_args.size() != 3) {
                    ThrowError("FAKELUA_SET_TABLE expects exactly 3 arguments", functioncall);
                }
                const auto tmp = std::format("flua_call_{}", tmp_var_counter_++);
                func_temp_decls_ << "    " << "CVar " << tmp << ";\n";
                *cur_output_ << GenTab() << std::format("FlSetTable({}, {}, {});\n", compiled_args[0], compiled_args[1], compiled_args[2]);
                *cur_output_ << GenTab() << std::format("SET_NIL({});\n", tmp);
                return tmp;
            } else if (local_func_names_.count(func_name)) {
                // Direct call to a function defined in the same C file
                call_expr = func_name + "(";
                for (size_t i = 0; i < compiled_args.size(); ++i) {
                    if (i > 0) {
                        call_expr += ", ";
                    }
                    call_expr += compiled_args[i];
                }
                call_expr += ")";
            } else {
                // Dynamic lookup by name in the global function registry.
                // JIT type comes from backend compile-time macro FAKELUA_JIT_TYPE.
                call_expr = std::format("FakeluaCallByName(_S, FAKELUA_JIT_TYPE, \"{}\", {}", func_name, compiled_args.size());
                for (const auto &arg: compiled_args) {
                    call_expr += ", " + arg;
                }
                call_expr += ")";
            }
        } else {
            ThrowError("complex function call expression is not supported", functioncall);
        }
    } else {
        ThrowError("complex function call expression is not supported", functioncall);
    }

    // Allocate a temp variable to hold the return value
    const auto tmp = std::format("flua_call_{}", tmp_var_counter_++);
    func_temp_decls_ << "    " << "CVar " << tmp << ";\n";
    *cur_output_ << GenTab() << tmp << " = " << call_expr << ";\n";

    return tmp;
}

}// namespace fakelua
