name: BuildWithASAN

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13

      - name: Prepare
        run: |
          sudo apt-get -y install libgccjit-13-dev
          dpkg -L libgccjit-13-dev
          sudo mv /usr/lib/gcc/x86_64-linux-gnu/13/include/libgccjit* /usr/include/
          sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/13/libgccjit.so /usr/lib/libgccjit.so
          
      - name: Build with asan
        run: |
          set -x
          rm build -rf
          mkdir build
          cd build
          export ASAN_OPTIONS=detect_leaks=0
          cmake -DUSE_ASAN=ON ..
          make -j8
          ctest -V
          ./bin/bench_mark
          cd ..
