name: BuildWithCOV

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13
          
      - name: Prepare
        run: |
          sudo apt-get -y install libgccjit-13-dev
          dpkg -L libgccjit-13-dev
          sudo mv /usr/lib/gcc/x86_64-linux-gnu/13/include/libgccjit* /usr/include/
          sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/13/libgccjit.so /usr/lib/libgccjit.so
          
      - name: Build with cov
        run: |
          set -x
          rm build -rf
          mkdir build
          cd build
          cmake -DUSE_COV=ON ..
          make -j8
          ctest -V
          ./bin/bench_mark
          ./bin/lua
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV }}
