name: BuildWithCOV

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13
          
      - name: Prepare
        run: |
          sudo apt-get -y install libgccjit-13-dev
          dpkg -L libgccjit-13-dev
          sudo mv /usr/lib/gcc/x86_64-linux-gnu/13/include/libgccjit* /usr/include/
          sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/13/libgccjit.so /usr/lib/libgccjit.so
          wget https://github.com/linux-test-project/lcov/releases/download/v2.0/lcov-2.0.tar.gz
          tar -xf lcov-2.0.tar.gz
          cd lcov-2.0/
          sudo make install
          yes|sudo perl -MCPAN -e 'install Capture::Tiny' 
          sudo apt-get install libdatetime-perl -y
          sudo rm /usr/bin/lcov -f
          sudo ln -s /usr/local/bin/lcov /usr/bin/lcov 
          lcov --version
          cd ..
          
      - name: Build with cov
        run: |
          set -x
          rm build -rf
          mkdir build
          cd build
          cmake -DUSE_COV=ON ..
          make -j8
          ctest -V
          ./bin/bench_mark
          ./bin/lua
          lcov --no-external --directory ./ --capture --output-file app.info --ignore-errors source 
          ls -l app.info
          lcov --list app.info
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV }} -f coverage.info || echo "Codecov did not collect coverage reports"
          
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV }}
      #     files: ${{ github.workspace }}/build/app.info
      #     verbose: true
