name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13

      - name: Build with cov
        run: |
          set -x
          rm build -rf
          mkdir build
          cd build
          cmake -DUSE_COV=ON ..
          make -j8
          ctest -V
          ./bin/bench_mark
          cd ..
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV }}
