name: BuildWithASAN

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13

      - name: Build with asan
        run: |
          set -x
          rm build -rf
          mkdir build
          cd build
          cmake -DUSE_ASAN=ON ..
          make -j8
          ctest -V
          ./bin/bench_mark
          cd ..
