name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV }}

      - run:   |
               sudo apt update
               sudo apt install gcc-10 g++-10
        shell: bash
  
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gdb
          gcc -v
          g++ -v
          gdb -v
          cmake --version
          set -x

      - name: Build
        run: |
          rm build -rf
          mkdir build
          cd build
          cmake ..
          make -j8
          ctest -V
          ./bin/bench_mark
          cd ..
        shell: bash
        env:
         CC:   gcc-10
         CXX:  g++-10
   
      - name: Build with asan
        run: |
          rm build -rf
          mkdir build
          cd build
          cmake -DUSE_ASAN=ON ..
          make -j8
          ctest -V
          ./bin/bench_mark
          cd ..
        shell: bash
        env:
         CC:   gcc-10
         CXX:  g++-10
