name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Env
        run: |
          echo "cur_home=$PWD" >> "$GITHUB_ENV"

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV }}

      - name: Build
        run: |
          set -x
          printf '%s\n' "$cur_home"
          cd $cur_home
          export PATH=$cur_home/GCC-13.2.0/bin:$PATH
          export LD_LIBRARY_PATH=$cur_home/GCC-13.2.0/lib64:$LD_LIBRARY_PATH
          ls -l $cur_home/GCC-13.2.0/lib64
          rm build -rf
          mkdir build
          cd build
          cmake ..
          make -j8
          ctest -V
          ./bin/bench_mark
          cd ..

      - name: Build with asan
        run: |
          set -x
          printf '%s\n' "$cur_home"
          cd $cur_home
          export PATH=$cur_home/GCC-13.2.0/bin:$PATH
          export LD_LIBRARY_PATH=$cur_home/GCC-13.2.0/lib64:$LD_LIBRARY_PATH
          rm build -rf
          mkdir build
          cd build
          cmake -DUSE_ASAN=ON ..
          make -j8
          ctest -V
          ./bin/bench_mark
          cd ..
