name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gdb
          gcc -v
          g++ -v
          gdb -v
          cmake --version

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j8
          gdb bin/unit_tests -ex r
          ctest -V
