name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13
          
      - name: Prepare
        run: |
          sudo apt-get -y install libgccjit-13-dev
          dpkg -L libgccjit-13-dev
          sudo mv /usr/lib/gcc/x86_64-linux-gnu/13/include/libgccjit* /usr/include/
          sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/13/libgccjit.so /usr/lib/libgccjit.so
          
      - name: Build
        run: |
          set -x
          wget https://github.com/danmar/cppcheck/archive/refs/tags/2.12.1.tar.gz
          tar -xf 2.12.1.tar.gz
          cd cppcheck-2.12.1
          mkdir build
          cd build
          cmake ..
          make -j8
          sudo make install
          cd ..
          cd ..
          cppcheck --version
